////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", 
// as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////
// AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
// If you edit this file, your edits WILL BE TERMINATED with
// extreme prejudice by the next build.
using OutSmart.DAXon.Transformation;using OutSmart.DAXon.Functions;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Lib
{
    public abstract class FeatureKeys
    {
        public const string ALLOW_EXTERNAL_FUNCTIONS = "http://saxon.sf.net/feature/allow-external-functions";
        public const string ALLOW_MULTITHREADING = "http://saxon.sf.net/feature/allow-multithreading";
        public const string ALLOW_OLD_JAVA_URI_FORMAT = "http://saxon.sf.net/feature/allow-old-java-uri-format";
        public const string ALLOW_SYNTAX_EXTENSIONS = "http://saxon.sf.net/feature/allowSyntaxExtensions";
        public const string ASSERTIONS_CAN_SEE_COMMENTS = "http://saxon.sf.net/feature/assertionsCanSeeComments";
        public const string COLLATION_URI_RESOLVER = "http://saxon.sf.net/feature/collation-uri-resolver";
        public const string COLLATION_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/collation-uri-resolver-class";
        public const string COLLECTION_FINDER = "http://saxon.sf.net/feature/collection-finder";
        public const string COLLECTION_FINDER_CLASS = "http://saxon.sf.net/feature/collection-finder-class";
        public const string COMPILE_WITH_TRACING = "http://saxon.sf.net/feature/compile-with-tracing";
        public const string CONFIGURATION = "http://saxon.sf.net/feature/configuration";
        public const string CONFIGURATION_FILE = "http://saxon.sf.net/feature/configuration-file";
        public const string DEBUG_BYTE_CODE = "http://saxon.sf.net/feature/debugByteCode";
        public const string DEBUG_BYTE_CODE_DIR = "http://saxon.sf.net/feature/debugByteCodeDir";
        public const string DEFAULT_COLLATION = "http://saxon.sf.net/feature/defaultCollation";
        public const string DEFAULT_COLLECTION = "http://saxon.sf.net/feature/defaultCollection";
        public const string DEFAULT_COUNTRY = "http://saxon.sf.net/feature/defaultCountry";
        public const string DEFAULT_LANGUAGE = "http://saxon.sf.net/feature/defaultLanguage";
        public const string DEFAULT_REGEX_ENGINE = "http://saxon.sf.net/feature/defaultRegexEngine";
        public const string DISABLE_XSL_EVALUATE = "http://saxon.sf.net/feature/disableXslEvaluate";
        public const string DISPLAY_BYTE_CODE = "http://saxon.sf.net/feature/displayByteCode";
        public const string DTD_VALIDATION = "http://saxon.sf.net/feature/validation";
        public const string DTD_VALIDATION_RECOVERABLE = "http://saxon.sf.net/feature/dtd-validation-recoverable";
        public const string EAGER_EVALUATION = "http://saxon.sf.net/feature/eagerEvaluation";
        public const string ENTITY_RESOLVER_CLASS = "http://saxon.sf.net/feature/entityResolverClass";
        public const string ENVIRONMENT_VARIABLE_RESOLVER = "http://saxon.sf.net/feature/environmentVariableResolver";
        public const string ENVIRONMENT_VARIABLE_RESOLVER_CLASS = "http://saxon.sf.net/feature/environmentVariableResolverClass";
        public const string ERROR_LISTENER_CLASS = "http://saxon.sf.net/feature/errorListenerClass";
        public const string EXPAND_ATTRIBUTE_DEFAULTS = "http://saxon.sf.net/feature/expandAttributeDefaults";
        public const string EXPATH_FILE_DELETE_TEMPORARY_FILES = "http://saxon.sf.net/feature/expathFileDeleteTemporaryFiles";
        public const string GENERATE_BYTE_CODE = "http://saxon.sf.net/feature/generateByteCode";
        public const string IGNORE_SAX_SOURCE_PARSER = "http://saxon.sf.net/feature/ignoreSAXSourceParser";
        public const string IMPLICIT_SCHEMA_IMPORTS = "http://saxon.sf.net/feature/implicitSchemaImports";
        public const string LAZY_CONSTRUCTION_MODE = "http://saxon.sf.net/feature/lazyConstructionMode";
        public const string LICENSE_FILE_LOCATION = "http://saxon.sf.net/feature/licenseFileLocation";
        public const string LINE_NUMBERING = "http://saxon.sf.net/feature/linenumbering";
        public const string MARK_DEFAULTED_ATTRIBUTES = "http://saxon.sf.net/feature/markDefaultedAttributes";
        public const string MAX_COMPILED_CLASSES = "http://saxon.sf.net/feature/maxCompiledClasses";
        public const string MESSAGE_EMITTER_CLASS = "http://saxon.sf.net/feature/messageEmitterClass";
        public const string MODULE_URI_RESOLVER = "http://saxon.sf.net/feature/moduleURIResolver";
        public const string MODULE_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/moduleURIResolverClass";
        public const string MONITOR_HOT_SPOT_BYTE_CODE = "http://saxon.sf.net/feature/monitorHotSpotByteCode";
        public const string MULTIPLE_SCHEMA_IMPORTS = "http://saxon.sf.net/feature/multipleSchemaImports";
        public const string NAME_POOL = "http://saxon.sf.net/feature/namePool";
        public const string OCCURRENCE_LIMITS = "http://saxon.sf.net/feature/occurrenceLimits";
        public const string OPTIMIZATION_LEVEL = "http://saxon.sf.net/feature/optimizationLevel";
        public const string OUTPUT_URI_RESOLVER = "http://saxon.sf.net/feature/outputURIResolver";
        public const string OUTPUT_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/outputURIResolverClass";
        public const string PRE_EVALUATE_DOC_FUNCTION = "http://saxon.sf.net/feature/preEvaluateDocFunction";
        public const string RECOGNIZE_URI_QUERY_PARAMETERS = "http://saxon.sf.net/feature/recognize-uri-query-parameters";
        public const string RECOVERY_POLICY = "http://saxon.sf.net/feature/recoveryPolicy";
        public const string RECOVERY_POLICY_NAME = "http://saxon.sf.net/feature/recoveryPolicyName";
        public const string RESULT_DOCUMENT_THREADS = "http://saxon.sf.net/feature/resultDocumentThreads";
        public const string RETAIN_DTD_ATTRIBUTE_TYPES = "http://saxon.sf.net/feature/retain-dtd-attribute-types";
        public const string SCHEMA_URI_RESOLVER = "http://saxon.sf.net/feature/schemaURIResolver";
        public const string SCHEMA_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/schemaURIResolverClass";
        public const string SCHEMA_VALIDATION = "http://saxon.sf.net/feature/schema-validation";
        public const string SCHEMA_VALIDATION_MODE = "http://saxon.sf.net/feature/schema-validation-mode";
        public const string SERIALIZER_FACTORY_CLASS = "http://saxon.sf.net/feature/serializerFactoryClass";
        public const string SOURCE_PARSER_CLASS = "http://saxon.sf.net/feature/sourceParserClass";
        public const string SOURCE_RESOLVER_CLASS = "http://saxon.sf.net/feature/sourceResolverClass";
        public const string STABLE_COLLECTION_URI = "http://saxon.sf.net/feature/stableCollectionUri";
        public const string STABLE_UNPARSED_TEXT = "http://saxon.sf.net/feature/stableUnparsedText";
        public const string STANDARD_ERROR_OUTPUT_FILE = "http://saxon.sf.net/feature/standardErrorOutputFile";
        public const string STREAMABILITY = "http://saxon.sf.net/feature/streamability";
        public const string STRICT_STREAMABILITY = "http://saxon.sf.net/feature/strictStreamability";
        public const string STREAMING_FALLBACK = "http://saxon.sf.net/feature/streamingFallback";
        public const string STRIP_WHITESPACE = "http://saxon.sf.net/feature/strip-whitespace";
        public const string STYLE_PARSER_CLASS = "http://saxon.sf.net/feature/styleParserClass";
        public const string SUPPRESS_EVALUATION_EXPIRY_WARNING = "http://saxon.sf.net/feature/suppressEvaluationExpiryWarning";
        public const string SUPPRESS_XPATH_WARNINGS = "http://saxon.sf.net/feature/suppressXPathWarnings";
        public const string SUPPRESS_XSLT_NAMESPACE_CHECK = "http://saxon.sf.net/feature/suppressXsltNamespaceCheck";
        public const string THRESHOLD_FOR_COMPILING_TYPES = "http://saxon.sf.net/feature/thresholdForCompilingTypes";
        public const string TIMING = "http://saxon.sf.net/feature/timing";
        public const string TRACE_EXTERNAL_FUNCTIONS = "http://saxon.sf.net/feature/trace-external-functions";
        public const string TRACE_LISTENER = "http://saxon.sf.net/feature/traceListener";
        public const string TRACE_LISTENER_CLASS = "http://saxon.sf.net/feature/traceListenerClass";
        public const string TRACE_LISTENER_OUTPUT_FILE = "http://saxon.sf.net/feature/traceListenerOutputFile";
        public const string TRACE_OPTIMIZER_DECISIONS = "http://saxon.sf.net/feature/trace-optimizer-decisions";
        public const string TREE_MODEL = "http://saxon.sf.net/feature/treeModel";
        public const string TREE_MODEL_NAME = "http://saxon.sf.net/feature/treeModelName";
        public const string UNPARSED_TEXT_URI_RESOLVER = "http://saxon.sf.net/feature/unparsedTextURIResolver";
        public const string UNPARSED_TEXT_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/unparsedTextURIResolverClass";
        public const string URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/uriResolverClass";
        public const string USE_PI_DISABLE_OUTPUT_ESCAPING = "http://saxon.sf.net/feature/use-pi-disable-output-escaping";
        public const string USE_TYPED_VALUE_CACHE = "http://saxon.sf.net/feature/use-typed-value-cache";
        public const string USE_XSI_SCHEMA_LOCATION = "http://saxon.sf.net/feature/useXsiSchemaLocation";
        public const string VALIDATION_COMMENTS = "http://saxon.sf.net/feature/validation-comments";
        public const string VALIDATION_WARNINGS = "http://saxon.sf.net/feature/validation-warnings";
        public const string VERSION_WARNING = "http://saxon.sf.net/feature/version-warning";
        public const string XINCLUDE = "http://saxon.sf.net/feature/xinclude-aware";
        public const string XML_VERSION = "http://saxon.sf.net/feature/xml-version";
        public const string XML_PARSER_FEATURE = "http://saxon.sf.net/feature/parserFeature?uri=";
        public const string XML_PARSER_PROPERTY = "http://saxon.sf.net/feature/parserProperty?uri=";
        public const string XQUERY_ALLOW_UPDATE = "http://saxon.sf.net/feature/xqueryAllowUpdate";
        public const string XQUERY_CONSTRUCTION_MODE = "http://saxon.sf.net/feature/xqueryConstructionMode";
        public const string XQUERY_DEFAULT_ELEMENT_NAMESPACE = "http://saxon.sf.net/feature/xqueryDefaultElementNamespace";
        public const string XQUERY_DEFAULT_FUNCTION_NAMESPACE = "http://saxon.sf.net/feature/xqueryDefaultFunctionNamespace";
        public const string XQUERY_EMPTY_LEAST = "http://saxon.sf.net/feature/xqueryEmptyLeast";
        public const string XQUERY_INHERIT_NAMESPACES = "http://saxon.sf.net/feature/xqueryInheritNamespaces";
        public const string XQUERY_MULTIPLE_MODULE_IMPORTS = "http://saxon.sf.net/feature/xqueryMultipleModuleImports";
        public const string XQUERY_PRESERVE_BOUNDARY_SPACE = "http://saxon.sf.net/feature/xqueryPreserveBoundarySpace";
        public const string XQUERY_PRESERVE_NAMESPACES = "http://saxon.sf.net/feature/xqueryPreserveNamespaces";
        public const string XQUERY_REQUIRED_CONTEXT_ITEM_TYPE = "http://saxon.sf.net/feature/xqueryRequiredContextItemType";
        public const string XQUERY_SCHEMA_AWARE = "http://saxon.sf.net/feature/xquerySchemaAware";
        public const string XQUERY_STATIC_ERROR_LISTENER_CLASS = "http://saxon.sf.net/feature/xqueryStaticErrorListenerClass";
        public const string XQUERY_VERSION = "http://saxon.sf.net/feature/xqueryVersion";
        public const string XSD_VERSION = "http://saxon.sf.net/feature/xsd-version";
        public const string XSLT_ENABLE_ASSERTIONS = "http://saxon.sf.net/feature/enableAssertions";
        public const string XSLT_INITIAL_MODE = "http://saxon.sf.net/feature/initialMode";
        public const string XSLT_INITIAL_TEMPLATE = "http://saxon.sf.net/feature/initialTemplate";
        public const string XSLT_SCHEMA_AWARE = "http://saxon.sf.net/feature/xsltSchemaAware";
        public const string XSLT_STATIC_ERROR_LISTENER_CLASS = "http://saxon.sf.net/feature/stylesheetErrorListener";
        public const string XSLT_STATIC_URI_RESOLVER_CLASS = "http://saxon.sf.net/feature/stylesheetURIResolver";
        public const string XSLT_VERSION = "http://saxon.sf.net/feature/xsltVersion";
        public const string REGEX_BACKTRACKING_LIMIT = "http://saxon.sf.net/feature/regexBacktrackingLimit";
        public const string XPATH_VERSION_FOR_XSD = "http://saxon.sf.net/feature/xpathVersionForXsd";
        public const string XPATH_VERSION_FOR_XSLT = "http://saxon.sf.net/feature/xpathVersionForXslt";
        public const string THRESHOLD_FOR_FUNCTION_INLINING = "http://saxon.sf.net/feature/thresholdForFunctionInlining";
        public const string THRESHOLD_FOR_HOTSPOT_BYTE_CODE = "http://saxon.sf.net/feature/thresholdForHotspotByteCode";
        public const string ALLOWED_PROTOCOLS = "http://saxon.sf.net/feature/allowedProtocols";
        public const string RETAIN_NODE_FOR_DIAGNOSTICS = "http://saxon.sf.net/feature/retainNodeForDiagnostics";
        public const string ALLOW_UNRESOLVED_SCHEMA_COMPONENTS = "http://saxon.sf.net/feature/allowUnresolvedSchemaComponents";
        public const string ZIP_URI_PATTERN = "http://saxon.sf.net/feature/zipUriPattern";
        public const string RESOURCE_RESOLVER = "http://saxon.sf.net/feature/saxon-resource-resolver";
        public const string RESOURCE_RESOLVER_CLASS = "http://saxon.sf.net/feature/saxon-resource-resolver-class"; // AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
    }
}