////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", 
// as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////
using System;using OutSmart.DAXon.Functions;

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Lib
{
    // AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
    // If you edit this file, your edits WILL BE TERMINATED with
    // extreme prejudice by the next build.
    public abstract class FeatureCode
    {
        /// <remarks>@seeFeature#ALLOW_EXTERNAL_FUNCTIONS</remarks>
        public const int ALLOW_EXTERNAL_FUNCTIONS = 1;
        /// <remarks>@seeFeature#ALLOW_MULTITHREADING</remarks>
        public const int ALLOW_MULTITHREADING = 2;
        /// <remarks>@seeFeature#ALLOW_OLD_JAVA_URI_FORMAT</remarks>
        public const int ALLOW_OLD_JAVA_URI_FORMAT = 3;
        /// <remarks>@seeFeature#ALLOW_SYNTAX_EXTENSIONS</remarks>
        public const int ALLOW_SYNTAX_EXTENSIONS = 4;
        /// <remarks>@seeFeature#ASSERTIONS_CAN_SEE_COMMENTS</remarks>
        public const int ASSERTIONS_CAN_SEE_COMMENTS = 5;
        /// <remarks>@seeFeature#COLLATION_URI_RESOLVER</remarks>
        public const int COLLATION_URI_RESOLVER = 6;
        /// <remarks>@seeFeature#COLLATION_URI_RESOLVER_CLASS</remarks>
        public const int COLLATION_URI_RESOLVER_CLASS = 7;
        /// <remarks>@seeFeature#COLLECTION_FINDER</remarks>
        public const int COLLECTION_FINDER = 8;
        /// <remarks>@seeFeature#COLLECTION_FINDER_CLASS</remarks>
        public const int COLLECTION_FINDER_CLASS = 9;
        /// <remarks>@seeFeature#COMPILE_WITH_TRACING</remarks>
        public const int COMPILE_WITH_TRACING = 12;
        /// <remarks>@seeFeature#CONFIGURATION</remarks>
        public const int CONFIGURATION = 13;
        /// <remarks>@seeFeature#CONFIGURATION_FILE</remarks>
        public const int CONFIGURATION_FILE = 14;
        /// <remarks>@seeFeature#DEBUG_BYTE_CODE</remarks>
        public const int DEBUG_BYTE_CODE = 15;
        /// <remarks>@seeFeature#DEBUG_BYTE_CODE_DIR</remarks>
        public const int DEBUG_BYTE_CODE_DIR = 16;
        /// <remarks>@seeFeature#DEFAULT_COLLATION</remarks>
        public const int DEFAULT_COLLATION = 17;
        /// <remarks>@seeFeature#DEFAULT_COLLECTION</remarks>
        public const int DEFAULT_COLLECTION = 18;
        /// <remarks>@seeFeature#DEFAULT_COUNTRY</remarks>
        public const int DEFAULT_COUNTRY = 19;
        /// <remarks>@seeFeature#DEFAULT_LANGUAGE</remarks>
        public const int DEFAULT_LANGUAGE = 20;
        /// <remarks>@seeFeature#DEFAULT_REGEX_ENGINE</remarks>
        public const int DEFAULT_REGEX_ENGINE = 21;
        /// <remarks>@seeFeature#DISABLE_XSL_EVALUATE</remarks>
        public const int DISABLE_XSL_EVALUATE = 22;
        /// <remarks>@seeFeature#DISPLAY_BYTE_CODE</remarks>
        public const int DISPLAY_BYTE_CODE = 23;
        /// <remarks>@seeFeature#DTD_VALIDATION</remarks>
        public const int DTD_VALIDATION = 24;
        /// <remarks>@seeFeature#DTD_VALIDATION_RECOVERABLE</remarks>
        public const int DTD_VALIDATION_RECOVERABLE = 25;
        /// <remarks>@seeFeature#EAGER_EVALUATION</remarks>
        public const int EAGER_EVALUATION = 26;
        /// <remarks>@seeFeature#ENTITY_RESOLVER_CLASS</remarks>
        public const int ENTITY_RESOLVER_CLASS = 27;
        /// <remarks>@seeFeature#ENVIRONMENT_VARIABLE_RESOLVER</remarks>
        public const int ENVIRONMENT_VARIABLE_RESOLVER = 28;
        /// <remarks>@seeFeature#ENVIRONMENT_VARIABLE_RESOLVER_CLASS</remarks>
        public const int ENVIRONMENT_VARIABLE_RESOLVER_CLASS = 29;
        /// <remarks>@seeFeature#ERROR_LISTENER_CLASS</remarks>
        public const int ERROR_LISTENER_CLASS = 30;
        /// <remarks>@seeFeature#EXPAND_ATTRIBUTE_DEFAULTS</remarks>
        public const int EXPAND_ATTRIBUTE_DEFAULTS = 31;
        /// <remarks>@seeFeature#EXPATH_FILE_DELETE_TEMPORARY_FILES</remarks>
        public const int EXPATH_FILE_DELETE_TEMPORARY_FILES = 32;
        /// <remarks>@seeFeature#GENERATE_BYTE_CODE</remarks>
        public const int GENERATE_BYTE_CODE = 33;
        /// <remarks>@seeFeature#IGNORE_SAX_SOURCE_PARSER</remarks>
        public const int IGNORE_SAX_SOURCE_PARSER = 34;
        /// <remarks>@seeFeature#IMPLICIT_SCHEMA_IMPORTS</remarks>
        public const int IMPLICIT_SCHEMA_IMPORTS = 35;
        /// <remarks>@seeFeature#LAZY_CONSTRUCTION_MODE</remarks>
        public const int LAZY_CONSTRUCTION_MODE = 36;
        /// <remarks>@seeFeature#LICENSE_FILE_LOCATION</remarks>
        public const int LICENSE_FILE_LOCATION = 37;
        /// <remarks>@seeFeature#LINE_NUMBERING</remarks>
        public const int LINE_NUMBERING = 38;
        /// <remarks>@seeFeature#MARK_DEFAULTED_ATTRIBUTES</remarks>
        public const int MARK_DEFAULTED_ATTRIBUTES = 39;
        /// <remarks>@seeFeature#MAX_COMPILED_CLASSES</remarks>
        public const int MAX_COMPILED_CLASSES = 40;
        /// <remarks>@seeFeature#MESSAGE_EMITTER_CLASS</remarks>
        public const int MESSAGE_EMITTER_CLASS = 41;
        /// <remarks>@seeFeature#MODULE_URI_RESOLVER</remarks>
        public const int MODULE_URI_RESOLVER = 42;
        /// <remarks>@seeFeature#MODULE_URI_RESOLVER_CLASS</remarks>
        public const int MODULE_URI_RESOLVER_CLASS = 43;
        /// <remarks>@seeFeature#MONITOR_HOT_SPOT_BYTE_CODE</remarks>
        public const int MONITOR_HOT_SPOT_BYTE_CODE = 44;
        /// <remarks>@seeFeature#MULTIPLE_SCHEMA_IMPORTS</remarks>
        public const int MULTIPLE_SCHEMA_IMPORTS = 45;
        /// <remarks>@seeFeature#NAME_POOL</remarks>
        public const int NAME_POOL = 46;
        /// <remarks>@seeFeature#OCCURRENCE_LIMITS</remarks>
        public const int OCCURRENCE_LIMITS = 47;
        /// <remarks>@seeFeature#OPTIMIZATION_LEVEL</remarks>
        public const int OPTIMIZATION_LEVEL = 48;
        /// <remarks>@seeFeature#OUTPUT_URI_RESOLVER</remarks>
        public const int OUTPUT_URI_RESOLVER = 49;
        /// <remarks>@seeFeature#OUTPUT_URI_RESOLVER_CLASS</remarks>
        public const int OUTPUT_URI_RESOLVER_CLASS = 50;
        /// <remarks>@seeFeature#PRE_EVALUATE_DOC_FUNCTION</remarks>
        public const int PRE_EVALUATE_DOC_FUNCTION = 51;
        /// <remarks>@seeFeature#RECOGNIZE_URI_QUERY_PARAMETERS</remarks>
        public const int RECOGNIZE_URI_QUERY_PARAMETERS = 53;
        /// <remarks>@seeFeature#RECOVERY_POLICY</remarks>
        public const int RECOVERY_POLICY = 54;
        /// <remarks>@seeFeature#RECOVERY_POLICY_NAME</remarks>
        public const int RECOVERY_POLICY_NAME = 55;
        /// <remarks>@seeFeature#RESULT_DOCUMENT_THREADS</remarks>
        public const int RESULT_DOCUMENT_THREADS = 56;
        /// <remarks>@seeFeature#RETAIN_DTD_ATTRIBUTE_TYPES</remarks>
        public const int RETAIN_DTD_ATTRIBUTE_TYPES = 57;
        /// <remarks>@seeFeature#SCHEMA_URI_RESOLVER</remarks>
        public const int SCHEMA_URI_RESOLVER = 58;
        /// <remarks>@seeFeature#SCHEMA_URI_RESOLVER_CLASS</remarks>
        public const int SCHEMA_URI_RESOLVER_CLASS = 59;
        /// <remarks>@seeFeature#SCHEMA_VALIDATION</remarks>
        public const int SCHEMA_VALIDATION = 60;
        /// <remarks>@seeFeature#SCHEMA_VALIDATION_MODE</remarks>
        public const int SCHEMA_VALIDATION_MODE = 61;
        /// <remarks>@seeFeature#SERIALIZER_FACTORY_CLASS</remarks>
        public const int SERIALIZER_FACTORY_CLASS = 62;
        /// <remarks>@seeFeature#SOURCE_PARSER_CLASS</remarks>
        public const int SOURCE_PARSER_CLASS = 63;
        /// <remarks>@seeFeature#SOURCE_RESOLVER_CLASS</remarks>
        public const int SOURCE_RESOLVER_CLASS = 64;
        /// <remarks>@seeFeature#STABLE_COLLECTION_URI</remarks>
        public const int STABLE_COLLECTION_URI = 65;
        /// <remarks>@seeFeature#STABLE_UNPARSED_TEXT</remarks>
        public const int STABLE_UNPARSED_TEXT = 66;
        /// <remarks>@seeFeature#STANDARD_ERROR_OUTPUT_FILE</remarks>
        public const int STANDARD_ERROR_OUTPUT_FILE = 67;
        /// <remarks>@seeFeature#STREAMABILITY</remarks>
        public const int STREAMABILITY = 68;
        /// <remarks>@seeFeature#STRICT_STREAMABILITY</remarks>
        public const int STRICT_STREAMABILITY = 69;
        /// <remarks>@seeFeature#STREAMING_FALLBACK</remarks>
        public const int STREAMING_FALLBACK = 70;
        /// <remarks>@seeFeature#STRIP_WHITESPACE</remarks>
        public const int STRIP_WHITESPACE = 71;
        /// <remarks>@seeFeature#STYLE_PARSER_CLASS</remarks>
        public const int STYLE_PARSER_CLASS = 72;
        /// <remarks>@seeFeature#SUPPRESS_EVALUATION_EXPIRY_WARNING</remarks>
        public const int SUPPRESS_EVALUATION_EXPIRY_WARNING = 73;
        /// <remarks>@seeFeature#SUPPRESS_XPATH_WARNINGS</remarks>
        public const int SUPPRESS_XPATH_WARNINGS = 74;
        /// <remarks>@seeFeature#SUPPRESS_XSLT_NAMESPACE_CHECK</remarks>
        public const int SUPPRESS_XSLT_NAMESPACE_CHECK = 75;
        /// <remarks>@seeFeature#THRESHOLD_FOR_COMPILING_TYPES</remarks>
        public const int THRESHOLD_FOR_COMPILING_TYPES = 76;
        /// <remarks>@seeFeature#TIMING</remarks>
        public const int TIMING = 77;
        /// <remarks>@seeFeature#TRACE_EXTERNAL_FUNCTIONS</remarks>
        public const int TRACE_EXTERNAL_FUNCTIONS = 78;
        /// <remarks>@seeFeature#TRACE_LISTENER</remarks>
        public const int TRACE_LISTENER = 79;
        /// <remarks>@seeFeature#TRACE_LISTENER_CLASS</remarks>
        public const int TRACE_LISTENER_CLASS = 80;
        /// <remarks>@seeFeature#TRACE_LISTENER_OUTPUT_FILE</remarks>
        public const int TRACE_LISTENER_OUTPUT_FILE = 81;
        /// <remarks>@seeFeature#TRACE_OPTIMIZER_DECISIONS</remarks>
        public const int TRACE_OPTIMIZER_DECISIONS = 82;
        /// <remarks>@seeFeature#TREE_MODEL</remarks>
        public const int TREE_MODEL = 83;
        /// <remarks>@seeFeature#TREE_MODEL_NAME</remarks>
        public const int TREE_MODEL_NAME = 84;
        /// <remarks>@seeFeature#UNPARSED_TEXT_URI_RESOLVER</remarks>
        public const int UNPARSED_TEXT_URI_RESOLVER = 85;
        /// <remarks>@seeFeature#UNPARSED_TEXT_URI_RESOLVER_CLASS</remarks>
        public const int UNPARSED_TEXT_URI_RESOLVER_CLASS = 86;
        /// <remarks>@seeFeature#URI_RESOLVER_CLASS</remarks>
        public const int URI_RESOLVER_CLASS = 87;
        /// <remarks>@seeFeature#USE_PI_DISABLE_OUTPUT_ESCAPING</remarks>
        public const int USE_PI_DISABLE_OUTPUT_ESCAPING = 88;
        /// <remarks>@seeFeature#USE_TYPED_VALUE_CACHE</remarks>
        public const int USE_TYPED_VALUE_CACHE = 89;
        /// <remarks>@seeFeature#USE_XSI_SCHEMA_LOCATION</remarks>
        public const int USE_XSI_SCHEMA_LOCATION = 90;
        /// <remarks>@seeFeature#VALIDATION_COMMENTS</remarks>
        public const int VALIDATION_COMMENTS = 91;
        /// <remarks>@seeFeature#VALIDATION_WARNINGS</remarks>
        public const int VALIDATION_WARNINGS = 92;
        /// <remarks>@seeFeature#VERSION_WARNING</remarks>
        public const int VERSION_WARNING = 93;
        /// <remarks>@seeFeature#XINCLUDE</remarks>
        public const int XINCLUDE = 94;
        /// <remarks>@seeFeature#XML_VERSION</remarks>
        public const int XML_VERSION = 95;
        /// <remarks>@seeFeature#XML_PARSER_FEATURE</remarks>
        public const int XML_PARSER_FEATURE = 96;
        /// <remarks>@seeFeature#XML_PARSER_PROPERTY</remarks>
        public const int XML_PARSER_PROPERTY = 97;
        /// <remarks>@seeFeature#XQUERY_ALLOW_UPDATE</remarks>
        public const int XQUERY_ALLOW_UPDATE = 98;
        /// <remarks>@seeFeature#XQUERY_CONSTRUCTION_MODE</remarks>
        public const int XQUERY_CONSTRUCTION_MODE = 99;
        /// <remarks>@seeFeature#XQUERY_DEFAULT_ELEMENT_NAMESPACE</remarks>
        public const int XQUERY_DEFAULT_ELEMENT_NAMESPACE = 100;
        /// <remarks>@seeFeature#XQUERY_DEFAULT_FUNCTION_NAMESPACE</remarks>
        public const int XQUERY_DEFAULT_FUNCTION_NAMESPACE = 101;
        /// <remarks>@seeFeature#XQUERY_EMPTY_LEAST</remarks>
        public const int XQUERY_EMPTY_LEAST = 102;
        /// <remarks>@seeFeature#XQUERY_INHERIT_NAMESPACES</remarks>
        public const int XQUERY_INHERIT_NAMESPACES = 103;
        /// <remarks>@seeFeature#XQUERY_MULTIPLE_MODULE_IMPORTS</remarks>
        public const int XQUERY_MULTIPLE_MODULE_IMPORTS = 104;
        /// <remarks>@seeFeature#XQUERY_PRESERVE_BOUNDARY_SPACE</remarks>
        public const int XQUERY_PRESERVE_BOUNDARY_SPACE = 105;
        /// <remarks>@seeFeature#XQUERY_PRESERVE_NAMESPACES</remarks>
        public const int XQUERY_PRESERVE_NAMESPACES = 106;
        /// <remarks>@seeFeature#XQUERY_REQUIRED_CONTEXT_ITEM_TYPE</remarks>
        public const int XQUERY_REQUIRED_CONTEXT_ITEM_TYPE = 107;
        /// <remarks>@seeFeature#XQUERY_SCHEMA_AWARE</remarks>
        public const int XQUERY_SCHEMA_AWARE = 108;
        /// <remarks>@seeFeature#XQUERY_STATIC_ERROR_LISTENER_CLASS</remarks>
        public const int XQUERY_STATIC_ERROR_LISTENER_CLASS = 109;
        /// <remarks>@seeFeature#XQUERY_VERSION</remarks>
        public const int XQUERY_VERSION = 110;
        /// <remarks>@seeFeature#XSD_VERSION</remarks>
        public const int XSD_VERSION = 111;
        /// <remarks>@seeFeature#XSLT_ENABLE_ASSERTIONS</remarks>
        public const int XSLT_ENABLE_ASSERTIONS = 112;
        /// <remarks>@seeFeature#XSLT_INITIAL_MODE</remarks>
        public const int XSLT_INITIAL_MODE = 113;
        /// <remarks>@seeFeature#XSLT_INITIAL_TEMPLATE</remarks>
        public const int XSLT_INITIAL_TEMPLATE = 114;
        /// <remarks>@seeFeature#XSLT_SCHEMA_AWARE</remarks>
        public const int XSLT_SCHEMA_AWARE = 115;
        /// <remarks>@seeFeature#XSLT_STATIC_ERROR_LISTENER_CLASS</remarks>
        public const int XSLT_STATIC_ERROR_LISTENER_CLASS = 116;
        /// <remarks>@seeFeature#XSLT_STATIC_URI_RESOLVER_CLASS</remarks>
        public const int XSLT_STATIC_URI_RESOLVER_CLASS = 117;
        /// <remarks>@seeFeature#XSLT_VERSION</remarks>
        public const int XSLT_VERSION = 118;
        /// <remarks>@seeFeature#REGEX_BACKTRACKING_LIMIT</remarks>
        public const int REGEX_BACKTRACKING_LIMIT = 119;
        /// <remarks>@seeFeature#XPATH_VERSION_FOR_XSD</remarks>
        public const int XPATH_VERSION_FOR_XSD = 120;
        /// <remarks>@seeFeature#XPATH_VERSION_FOR_XSLT</remarks>
        public const int XPATH_VERSION_FOR_XSLT = 121;
        /// <remarks>@seeFeature#THRESHOLD_FOR_FUNCTION_INLINING</remarks>
        public const int THRESHOLD_FOR_FUNCTION_INLINING = 122;
        /// <remarks>@seeFeature#THRESHOLD_FOR_HOTSPOT_BYTE_CODE</remarks>
        public const int THRESHOLD_FOR_HOTSPOT_BYTE_CODE = 123;
        /// <remarks>@seeFeature#ALLOWED_PROTOCOLS</remarks>
        public const int ALLOWED_PROTOCOLS = 124;
        /// <remarks>@seeFeature#RETAIN_NODE_FOR_DIAGNOSTICS</remarks>
        public const int RETAIN_NODE_FOR_DIAGNOSTICS = 125;
        /// <remarks>@seeFeature#ALLOW_UNRESOLVED_SCHEMA_COMPONENTS</remarks>
        public const int ALLOW_UNRESOLVED_SCHEMA_COMPONENTS = 126;
        /// <remarks>@seeFeature#ZIP_URI_PATTERN</remarks>
        public const int ZIP_URI_PATTERN = 127;
        /// <remarks>@seeFeature#RESOURCE_RESOLVER</remarks>
        public const int RESOURCE_RESOLVER = 128;
        /// <remarks>@seeFeature#RESOURCE_RESOLVER_CLASS</remarks>
        public const int RESOURCE_RESOLVER_CLASS = 129;
        public const int MAX = 129;
    }
}