////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", 
// as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////
using System;using OutSmart.DAXon.Functions;

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Core;
using OutSmart.DAXon.Model;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Lib
{
    // AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
    // If you edit this file, your edits WILL BE TERMINATED with
    // extreme prejudice by the next build.
    public class FeatureData
    {

        public static List<FeatureData> featureList = new List<FeatureData>();
        public string uri;
        public int code;
        public string editions;
        public System.Type type;
        public object defaultValue;
        public FeatureData(string uri, int code, string editions, System.Type type, object defaultValue)
        {
            this.uri = uri;
            this.code = code;
            this.editions = editions;
            this.type = type;
            this.defaultValue = defaultValue;
        }
        public static void Init()
        {
            featureList.Add(new FeatureData(FeatureKeys.ALLOW_EXTERNAL_FUNCTIONS, FeatureCode.ALLOW_EXTERNAL_FUNCTIONS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ALLOW_MULTITHREADING, FeatureCode.ALLOW_MULTITHREADING, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ALLOW_OLD_JAVA_URI_FORMAT, FeatureCode.ALLOW_OLD_JAVA_URI_FORMAT, "PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ALLOW_SYNTAX_EXTENSIONS, FeatureCode.ALLOW_SYNTAX_EXTENSIONS, "PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ASSERTIONS_CAN_SEE_COMMENTS, FeatureCode.ASSERTIONS_CAN_SEE_COMMENTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.COLLATION_URI_RESOLVER, FeatureCode.COLLATION_URI_RESOLVER, "HE PE EE", typeof(ICollationURIResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.COLLATION_URI_RESOLVER_CLASS, FeatureCode.COLLATION_URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.COLLECTION_FINDER, FeatureCode.COLLECTION_FINDER, "HE PE EE", typeof(ICollectionFinder), null));
            featureList.Add(new FeatureData(FeatureKeys.COLLECTION_FINDER_CLASS, FeatureCode.COLLECTION_FINDER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.COMPILE_WITH_TRACING, FeatureCode.COMPILE_WITH_TRACING, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.CONFIGURATION, FeatureCode.CONFIGURATION, "HE PE EE", typeof(Configuration), null));
            featureList.Add(new FeatureData(FeatureKeys.CONFIGURATION_FILE, FeatureCode.CONFIGURATION_FILE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEBUG_BYTE_CODE, FeatureCode.DEBUG_BYTE_CODE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.DEBUG_BYTE_CODE_DIR, FeatureCode.DEBUG_BYTE_CODE_DIR, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEFAULT_COLLATION, FeatureCode.DEFAULT_COLLATION, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEFAULT_COLLECTION, FeatureCode.DEFAULT_COLLECTION, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEFAULT_COUNTRY, FeatureCode.DEFAULT_COUNTRY, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEFAULT_LANGUAGE, FeatureCode.DEFAULT_LANGUAGE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DEFAULT_REGEX_ENGINE, FeatureCode.DEFAULT_REGEX_ENGINE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.DISABLE_XSL_EVALUATE, FeatureCode.DISABLE_XSL_EVALUATE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.DISPLAY_BYTE_CODE, FeatureCode.DISPLAY_BYTE_CODE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.DTD_VALIDATION, FeatureCode.DTD_VALIDATION, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.DTD_VALIDATION_RECOVERABLE, FeatureCode.DTD_VALIDATION_RECOVERABLE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.EAGER_EVALUATION, FeatureCode.EAGER_EVALUATION, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ENTITY_RESOLVER_CLASS, FeatureCode.ENTITY_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.ENVIRONMENT_VARIABLE_RESOLVER, FeatureCode.ENVIRONMENT_VARIABLE_RESOLVER, "HE PE EE", typeof(IEnvironmentVariableResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.ENVIRONMENT_VARIABLE_RESOLVER_CLASS, FeatureCode.ENVIRONMENT_VARIABLE_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.ERROR_LISTENER_CLASS, FeatureCode.ERROR_LISTENER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.EXPAND_ATTRIBUTE_DEFAULTS, FeatureCode.EXPAND_ATTRIBUTE_DEFAULTS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.EXPATH_FILE_DELETE_TEMPORARY_FILES, FeatureCode.EXPATH_FILE_DELETE_TEMPORARY_FILES, "PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.GENERATE_BYTE_CODE, FeatureCode.GENERATE_BYTE_CODE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.IGNORE_SAX_SOURCE_PARSER, FeatureCode.IGNORE_SAX_SOURCE_PARSER, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.IMPLICIT_SCHEMA_IMPORTS, FeatureCode.IMPLICIT_SCHEMA_IMPORTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.LAZY_CONSTRUCTION_MODE, FeatureCode.LAZY_CONSTRUCTION_MODE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.LICENSE_FILE_LOCATION, FeatureCode.LICENSE_FILE_LOCATION, "PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.LINE_NUMBERING, FeatureCode.LINE_NUMBERING, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.MARK_DEFAULTED_ATTRIBUTES, FeatureCode.MARK_DEFAULTED_ATTRIBUTES, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.MAX_COMPILED_CLASSES, FeatureCode.MAX_COMPILED_CLASSES, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.MESSAGE_EMITTER_CLASS, FeatureCode.MESSAGE_EMITTER_CLASS, "HE PE EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.MODULE_URI_RESOLVER, FeatureCode.MODULE_URI_RESOLVER, "HE PE EE", typeof(IModuleURIResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.MODULE_URI_RESOLVER_CLASS, FeatureCode.MODULE_URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.MONITOR_HOT_SPOT_BYTE_CODE, FeatureCode.MONITOR_HOT_SPOT_BYTE_CODE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.MULTIPLE_SCHEMA_IMPORTS, FeatureCode.MULTIPLE_SCHEMA_IMPORTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.NAME_POOL, FeatureCode.NAME_POOL, "HE PE EE", typeof(NamePool), null));
            featureList.Add(new FeatureData(FeatureKeys.OCCURRENCE_LIMITS, FeatureCode.OCCURRENCE_LIMITS, "EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.OPTIMIZATION_LEVEL, FeatureCode.OPTIMIZATION_LEVEL, "HE PE EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.OUTPUT_URI_RESOLVER, FeatureCode.OUTPUT_URI_RESOLVER, "HE PE EE", typeof(IOutputURIResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.OUTPUT_URI_RESOLVER_CLASS, FeatureCode.OUTPUT_URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.PRE_EVALUATE_DOC_FUNCTION, FeatureCode.PRE_EVALUATE_DOC_FUNCTION, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.RECOGNIZE_URI_QUERY_PARAMETERS, FeatureCode.RECOGNIZE_URI_QUERY_PARAMETERS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.RECOVERY_POLICY, FeatureCode.RECOVERY_POLICY, "HE PE EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.RECOVERY_POLICY_NAME, FeatureCode.RECOVERY_POLICY_NAME, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.RESULT_DOCUMENT_THREADS, FeatureCode.RESULT_DOCUMENT_THREADS, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.RETAIN_DTD_ATTRIBUTE_TYPES, FeatureCode.RETAIN_DTD_ATTRIBUTE_TYPES, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.SCHEMA_URI_RESOLVER, FeatureCode.SCHEMA_URI_RESOLVER, "EE", typeof(ISchemaURIResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.SCHEMA_URI_RESOLVER_CLASS, FeatureCode.SCHEMA_URI_RESOLVER_CLASS, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.SCHEMA_VALIDATION, FeatureCode.SCHEMA_VALIDATION, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.SCHEMA_VALIDATION_MODE, FeatureCode.SCHEMA_VALIDATION_MODE, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.SERIALIZER_FACTORY_CLASS, FeatureCode.SERIALIZER_FACTORY_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.SOURCE_PARSER_CLASS, FeatureCode.SOURCE_PARSER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.SOURCE_RESOLVER_CLASS, FeatureCode.SOURCE_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.STABLE_COLLECTION_URI, FeatureCode.STABLE_COLLECTION_URI, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.STABLE_UNPARSED_TEXT, FeatureCode.STABLE_UNPARSED_TEXT, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.STANDARD_ERROR_OUTPUT_FILE, FeatureCode.STANDARD_ERROR_OUTPUT_FILE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.STREAMABILITY, FeatureCode.STREAMABILITY, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.STRICT_STREAMABILITY, FeatureCode.STRICT_STREAMABILITY, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.STREAMING_FALLBACK, FeatureCode.STREAMING_FALLBACK, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.STRIP_WHITESPACE, FeatureCode.STRIP_WHITESPACE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.STYLE_PARSER_CLASS, FeatureCode.STYLE_PARSER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.SUPPRESS_EVALUATION_EXPIRY_WARNING, FeatureCode.SUPPRESS_EVALUATION_EXPIRY_WARNING, "PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.SUPPRESS_XPATH_WARNINGS, FeatureCode.SUPPRESS_XPATH_WARNINGS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.SUPPRESS_XSLT_NAMESPACE_CHECK, FeatureCode.SUPPRESS_XSLT_NAMESPACE_CHECK, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.THRESHOLD_FOR_COMPILING_TYPES, FeatureCode.THRESHOLD_FOR_COMPILING_TYPES, "HE PE EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.TIMING, FeatureCode.TIMING, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.TRACE_EXTERNAL_FUNCTIONS, FeatureCode.TRACE_EXTERNAL_FUNCTIONS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.TRACE_LISTENER, FeatureCode.TRACE_LISTENER, "HE PE EE", typeof(ITraceListener), null));
            featureList.Add(new FeatureData(FeatureKeys.TRACE_LISTENER_CLASS, FeatureCode.TRACE_LISTENER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.TRACE_LISTENER_OUTPUT_FILE, FeatureCode.TRACE_LISTENER_OUTPUT_FILE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.TRACE_OPTIMIZER_DECISIONS, FeatureCode.TRACE_OPTIMIZER_DECISIONS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.TREE_MODEL, FeatureCode.TREE_MODEL, "HE PE EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.TREE_MODEL_NAME, FeatureCode.TREE_MODEL_NAME, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.UNPARSED_TEXT_URI_RESOLVER, FeatureCode.UNPARSED_TEXT_URI_RESOLVER, "HE PE EE", typeof(IUnparsedTextURIResolver), null));
            featureList.Add(new FeatureData(FeatureKeys.UNPARSED_TEXT_URI_RESOLVER_CLASS, FeatureCode.UNPARSED_TEXT_URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.URI_RESOLVER_CLASS, FeatureCode.URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.USE_PI_DISABLE_OUTPUT_ESCAPING, FeatureCode.USE_PI_DISABLE_OUTPUT_ESCAPING, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.USE_TYPED_VALUE_CACHE, FeatureCode.USE_TYPED_VALUE_CACHE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.USE_XSI_SCHEMA_LOCATION, FeatureCode.USE_XSI_SCHEMA_LOCATION, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.VALIDATION_COMMENTS, FeatureCode.VALIDATION_COMMENTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.VALIDATION_WARNINGS, FeatureCode.VALIDATION_WARNINGS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.VERSION_WARNING, FeatureCode.VERSION_WARNING, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XINCLUDE, FeatureCode.XINCLUDE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XML_VERSION, FeatureCode.XML_VERSION, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XML_PARSER_FEATURE, FeatureCode.XML_PARSER_FEATURE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XML_PARSER_PROPERTY, FeatureCode.XML_PARSER_PROPERTY, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_ALLOW_UPDATE, FeatureCode.XQUERY_ALLOW_UPDATE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_CONSTRUCTION_MODE, FeatureCode.XQUERY_CONSTRUCTION_MODE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_DEFAULT_ELEMENT_NAMESPACE, FeatureCode.XQUERY_DEFAULT_ELEMENT_NAMESPACE, "HE PE EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_DEFAULT_FUNCTION_NAMESPACE, FeatureCode.XQUERY_DEFAULT_FUNCTION_NAMESPACE, "HE PE EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_EMPTY_LEAST, FeatureCode.XQUERY_EMPTY_LEAST, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_INHERIT_NAMESPACES, FeatureCode.XQUERY_INHERIT_NAMESPACES, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_MULTIPLE_MODULE_IMPORTS, FeatureCode.XQUERY_MULTIPLE_MODULE_IMPORTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_PRESERVE_BOUNDARY_SPACE, FeatureCode.XQUERY_PRESERVE_BOUNDARY_SPACE, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_PRESERVE_NAMESPACES, FeatureCode.XQUERY_PRESERVE_NAMESPACES, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_REQUIRED_CONTEXT_ITEM_TYPE, FeatureCode.XQUERY_REQUIRED_CONTEXT_ITEM_TYPE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_SCHEMA_AWARE, FeatureCode.XQUERY_SCHEMA_AWARE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_STATIC_ERROR_LISTENER_CLASS, FeatureCode.XQUERY_STATIC_ERROR_LISTENER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XQUERY_VERSION, FeatureCode.XQUERY_VERSION, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSD_VERSION, FeatureCode.XSD_VERSION, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_ENABLE_ASSERTIONS, FeatureCode.XSLT_ENABLE_ASSERTIONS, "HE PE EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_INITIAL_MODE, FeatureCode.XSLT_INITIAL_MODE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_INITIAL_TEMPLATE, FeatureCode.XSLT_INITIAL_TEMPLATE, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_SCHEMA_AWARE, FeatureCode.XSLT_SCHEMA_AWARE, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_STATIC_ERROR_LISTENER_CLASS, FeatureCode.XSLT_STATIC_ERROR_LISTENER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_STATIC_URI_RESOLVER_CLASS, FeatureCode.XSLT_STATIC_URI_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.XSLT_VERSION, FeatureCode.XSLT_VERSION, "HE PE EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.REGEX_BACKTRACKING_LIMIT, FeatureCode.REGEX_BACKTRACKING_LIMIT, "HE PE EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.XPATH_VERSION_FOR_XSD, FeatureCode.XPATH_VERSION_FOR_XSD, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.XPATH_VERSION_FOR_XSLT, FeatureCode.XPATH_VERSION_FOR_XSLT, "HE PE EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.THRESHOLD_FOR_FUNCTION_INLINING, FeatureCode.THRESHOLD_FOR_FUNCTION_INLINING, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.THRESHOLD_FOR_HOTSPOT_BYTE_CODE, FeatureCode.THRESHOLD_FOR_HOTSPOT_BYTE_CODE, "EE", typeof(int), null));
            featureList.Add(new FeatureData(FeatureKeys.ALLOWED_PROTOCOLS, FeatureCode.ALLOWED_PROTOCOLS, "EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.RETAIN_NODE_FOR_DIAGNOSTICS, FeatureCode.RETAIN_NODE_FOR_DIAGNOSTICS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ALLOW_UNRESOLVED_SCHEMA_COMPONENTS, FeatureCode.ALLOW_UNRESOLVED_SCHEMA_COMPONENTS, "EE", typeof(bool), false));
            featureList.Add(new FeatureData(FeatureKeys.ZIP_URI_PATTERN, FeatureCode.ZIP_URI_PATTERN, "EE", typeof(string), null));
            featureList.Add(new FeatureData(FeatureKeys.RESOURCE_RESOLVER, FeatureCode.RESOURCE_RESOLVER, "HE PE EE", typeof(object), null));
            featureList.Add(new FeatureData(FeatureKeys.RESOURCE_RESOLVER_CLASS, FeatureCode.RESOURCE_RESOLVER_CLASS, "HE PE EE", typeof(string), null));
        }
    }
}