////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", 
// as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////
using System;using OutSmart.DAXon.Functions;

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Core;
using OutSmart.DAXon.Model;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Lib
{
    // AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
    // If you edit this file, your edits WILL BE TERMINATED with
    // extreme prejudice by the next build.
    public class Feature<T>
    {

        public static readonly Feature<bool> ALLOW_EXTERNAL_FUNCTIONS = new Feature<bool>(1, "http://saxon.sf.net/feature/allow-external-functions");
        public static readonly Feature<bool> ALLOW_MULTITHREADING = new Feature<bool>(2, "http://saxon.sf.net/feature/allow-multithreading");
        public static readonly Feature<bool> ALLOW_OLD_JAVA_URI_FORMAT = new Feature<bool>(3, "http://saxon.sf.net/feature/allow-old-java-uri-format");
        public static readonly Feature<bool> ALLOW_SYNTAX_EXTENSIONS = new Feature<bool>(4, "http://saxon.sf.net/feature/allowSyntaxExtensions");
        public static readonly Feature<bool> ASSERTIONS_CAN_SEE_COMMENTS = new Feature<bool>(5, "http://saxon.sf.net/feature/assertionsCanSeeComments");
        public static readonly Feature<ICollationURIResolver> COLLATION_URI_RESOLVER = new Feature<ICollationURIResolver>(6, "http://saxon.sf.net/feature/collation-uri-resolver");
        public static readonly Feature<string> COLLATION_URI_RESOLVER_CLASS = new Feature<string>(7, "http://saxon.sf.net/feature/collation-uri-resolver-class");
        public static readonly Feature<ICollectionFinder> COLLECTION_FINDER = new Feature<ICollectionFinder>(8, "http://saxon.sf.net/feature/collection-finder");
        public static readonly Feature<string> COLLECTION_FINDER_CLASS = new Feature<string>(9, "http://saxon.sf.net/feature/collection-finder-class");
        public static readonly Feature<bool> COMPILE_WITH_TRACING = new Feature<bool>(12, "http://saxon.sf.net/feature/compile-with-tracing");
        public static readonly Feature<Configuration> CONFIGURATION = new Feature<Configuration>(13, "http://saxon.sf.net/feature/configuration");
        public static readonly Feature<string> CONFIGURATION_FILE = new Feature<string>(14, "http://saxon.sf.net/feature/configuration-file");
        public static readonly Feature<bool> DEBUG_BYTE_CODE = new Feature<bool>(15, "http://saxon.sf.net/feature/debugByteCode");
        public static readonly Feature<string> DEBUG_BYTE_CODE_DIR = new Feature<string>(16, "http://saxon.sf.net/feature/debugByteCodeDir");
        public static readonly Feature<string> DEFAULT_COLLATION = new Feature<string>(17, "http://saxon.sf.net/feature/defaultCollation");
        public static readonly Feature<string> DEFAULT_COLLECTION = new Feature<string>(18, "http://saxon.sf.net/feature/defaultCollection");
        public static readonly Feature<string> DEFAULT_COUNTRY = new Feature<string>(19, "http://saxon.sf.net/feature/defaultCountry");
        public static readonly Feature<string> DEFAULT_LANGUAGE = new Feature<string>(20, "http://saxon.sf.net/feature/defaultLanguage");
        public static readonly Feature<string> DEFAULT_REGEX_ENGINE = new Feature<string>(21, "http://saxon.sf.net/feature/defaultRegexEngine");
        public static readonly Feature<bool> DISABLE_XSL_EVALUATE = new Feature<bool>(22, "http://saxon.sf.net/feature/disableXslEvaluate");
        public static readonly Feature<bool> DISPLAY_BYTE_CODE = new Feature<bool>(23, "http://saxon.sf.net/feature/displayByteCode");
        public static readonly Feature<bool> DTD_VALIDATION = new Feature<bool>(24, "http://saxon.sf.net/feature/validation");
        public static readonly Feature<bool> DTD_VALIDATION_RECOVERABLE = new Feature<bool>(25, "http://saxon.sf.net/feature/dtd-validation-recoverable");
        public static readonly Feature<bool> EAGER_EVALUATION = new Feature<bool>(26, "http://saxon.sf.net/feature/eagerEvaluation");
        public static readonly Feature<string> ENTITY_RESOLVER_CLASS = new Feature<string>(27, "http://saxon.sf.net/feature/entityResolverClass");
        public static readonly Feature<IEnvironmentVariableResolver> ENVIRONMENT_VARIABLE_RESOLVER = new Feature<IEnvironmentVariableResolver>(28, "http://saxon.sf.net/feature/environmentVariableResolver");
        public static readonly Feature<string> ENVIRONMENT_VARIABLE_RESOLVER_CLASS = new Feature<string>(29, "http://saxon.sf.net/feature/environmentVariableResolverClass");
        public static readonly Feature<string> ERROR_LISTENER_CLASS = new Feature<string>(30, "http://saxon.sf.net/feature/errorListenerClass");
        public static readonly Feature<bool> EXPAND_ATTRIBUTE_DEFAULTS = new Feature<bool>(31, "http://saxon.sf.net/feature/expandAttributeDefaults");
        public static readonly Feature<bool> EXPATH_FILE_DELETE_TEMPORARY_FILES = new Feature<bool>(32, "http://saxon.sf.net/feature/expathFileDeleteTemporaryFiles");
        public static readonly Feature<bool> GENERATE_BYTE_CODE = new Feature<bool>(33, "http://saxon.sf.net/feature/generateByteCode");
        public static readonly Feature<bool> IGNORE_SAX_SOURCE_PARSER = new Feature<bool>(34, "http://saxon.sf.net/feature/ignoreSAXSourceParser");
        public static readonly Feature<bool> IMPLICIT_SCHEMA_IMPORTS = new Feature<bool>(35, "http://saxon.sf.net/feature/implicitSchemaImports");
        public static readonly Feature<bool> LAZY_CONSTRUCTION_MODE = new Feature<bool>(36, "http://saxon.sf.net/feature/lazyConstructionMode");
        public static readonly Feature<string> LICENSE_FILE_LOCATION = new Feature<string>(37, "http://saxon.sf.net/feature/licenseFileLocation");
        public static readonly Feature<bool> LINE_NUMBERING = new Feature<bool>(38, "http://saxon.sf.net/feature/linenumbering");
        public static readonly Feature<bool> MARK_DEFAULTED_ATTRIBUTES = new Feature<bool>(39, "http://saxon.sf.net/feature/markDefaultedAttributes");
        public static readonly Feature<int> MAX_COMPILED_CLASSES = new Feature<int>(40, "http://saxon.sf.net/feature/maxCompiledClasses");
        public static readonly Feature<object> MESSAGE_EMITTER_CLASS = new Feature<object>(41, "http://saxon.sf.net/feature/messageEmitterClass");
        public static readonly Feature<IModuleURIResolver> MODULE_URI_RESOLVER = new Feature<IModuleURIResolver>(42, "http://saxon.sf.net/feature/moduleURIResolver");
        public static readonly Feature<string> MODULE_URI_RESOLVER_CLASS = new Feature<string>(43, "http://saxon.sf.net/feature/moduleURIResolverClass");
        public static readonly Feature<bool> MONITOR_HOT_SPOT_BYTE_CODE = new Feature<bool>(44, "http://saxon.sf.net/feature/monitorHotSpotByteCode");
        public static readonly Feature<bool> MULTIPLE_SCHEMA_IMPORTS = new Feature<bool>(45, "http://saxon.sf.net/feature/multipleSchemaImports");
        public static readonly Feature<NamePool> NAME_POOL = new Feature<NamePool>(46, "http://saxon.sf.net/feature/namePool");
        public static readonly Feature<object> OCCURRENCE_LIMITS = new Feature<object>(47, "http://saxon.sf.net/feature/occurrenceLimits");
        public static readonly Feature<object> OPTIMIZATION_LEVEL = new Feature<object>(48, "http://saxon.sf.net/feature/optimizationLevel");
        public static readonly Feature<IOutputURIResolver> OUTPUT_URI_RESOLVER = new Feature<IOutputURIResolver>(49, "http://saxon.sf.net/feature/outputURIResolver");
        public static readonly Feature<string> OUTPUT_URI_RESOLVER_CLASS = new Feature<string>(50, "http://saxon.sf.net/feature/outputURIResolverClass");
        public static readonly Feature<bool> PRE_EVALUATE_DOC_FUNCTION = new Feature<bool>(51, "http://saxon.sf.net/feature/preEvaluateDocFunction");
        public static readonly Feature<bool> RECOGNIZE_URI_QUERY_PARAMETERS = new Feature<bool>(53, "http://saxon.sf.net/feature/recognize-uri-query-parameters");
        public static readonly Feature<int> RECOVERY_POLICY = new Feature<int>(54, "http://saxon.sf.net/feature/recoveryPolicy");
        public static readonly Feature<string> RECOVERY_POLICY_NAME = new Feature<string>(55, "http://saxon.sf.net/feature/recoveryPolicyName");
        public static readonly Feature<int> RESULT_DOCUMENT_THREADS = new Feature<int>(56, "http://saxon.sf.net/feature/resultDocumentThreads");
        public static readonly Feature<bool> RETAIN_DTD_ATTRIBUTE_TYPES = new Feature<bool>(57, "http://saxon.sf.net/feature/retain-dtd-attribute-types");
        public static readonly Feature<ISchemaURIResolver> SCHEMA_URI_RESOLVER = new Feature<ISchemaURIResolver>(58, "http://saxon.sf.net/feature/schemaURIResolver");
        public static readonly Feature<string> SCHEMA_URI_RESOLVER_CLASS = new Feature<string>(59, "http://saxon.sf.net/feature/schemaURIResolverClass");
        public static readonly Feature<int> SCHEMA_VALIDATION = new Feature<int>(60, "http://saxon.sf.net/feature/schema-validation");
        public static readonly Feature<string> SCHEMA_VALIDATION_MODE = new Feature<string>(61, "http://saxon.sf.net/feature/schema-validation-mode");
        public static readonly Feature<string> SERIALIZER_FACTORY_CLASS = new Feature<string>(62, "http://saxon.sf.net/feature/serializerFactoryClass");
        public static readonly Feature<string> SOURCE_PARSER_CLASS = new Feature<string>(63, "http://saxon.sf.net/feature/sourceParserClass");
        public static readonly Feature<string> SOURCE_RESOLVER_CLASS = new Feature<string>(64, "http://saxon.sf.net/feature/sourceResolverClass");
        public static readonly Feature<bool> STABLE_COLLECTION_URI = new Feature<bool>(65, "http://saxon.sf.net/feature/stableCollectionUri");
        public static readonly Feature<bool> STABLE_UNPARSED_TEXT = new Feature<bool>(66, "http://saxon.sf.net/feature/stableUnparsedText");
        public static readonly Feature<string> STANDARD_ERROR_OUTPUT_FILE = new Feature<string>(67, "http://saxon.sf.net/feature/standardErrorOutputFile");
        public static readonly Feature<string> STREAMABILITY = new Feature<string>(68, "http://saxon.sf.net/feature/streamability");
        public static readonly Feature<bool> STRICT_STREAMABILITY = new Feature<bool>(69, "http://saxon.sf.net/feature/strictStreamability");
        public static readonly Feature<bool> STREAMING_FALLBACK = new Feature<bool>(70, "http://saxon.sf.net/feature/streamingFallback");
        public static readonly Feature<string> STRIP_WHITESPACE = new Feature<string>(71, "http://saxon.sf.net/feature/strip-whitespace");
        public static readonly Feature<string> STYLE_PARSER_CLASS = new Feature<string>(72, "http://saxon.sf.net/feature/styleParserClass");
        public static readonly Feature<bool> SUPPRESS_EVALUATION_EXPIRY_WARNING = new Feature<bool>(73, "http://saxon.sf.net/feature/suppressEvaluationExpiryWarning");
        public static readonly Feature<bool> SUPPRESS_XPATH_WARNINGS = new Feature<bool>(74, "http://saxon.sf.net/feature/suppressXPathWarnings");
        public static readonly Feature<bool> SUPPRESS_XSLT_NAMESPACE_CHECK = new Feature<bool>(75, "http://saxon.sf.net/feature/suppressXsltNamespaceCheck");
        public static readonly Feature<int> THRESHOLD_FOR_COMPILING_TYPES = new Feature<int>(76, "http://saxon.sf.net/feature/thresholdForCompilingTypes");
        public static readonly Feature<bool> TIMING = new Feature<bool>(77, "http://saxon.sf.net/feature/timing");
        public static readonly Feature<bool> TRACE_EXTERNAL_FUNCTIONS = new Feature<bool>(78, "http://saxon.sf.net/feature/trace-external-functions");
        public static readonly Feature<ITraceListener> TRACE_LISTENER = new Feature<ITraceListener>(79, "http://saxon.sf.net/feature/traceListener");
        public static readonly Feature<string> TRACE_LISTENER_CLASS = new Feature<string>(80, "http://saxon.sf.net/feature/traceListenerClass");
        public static readonly Feature<string> TRACE_LISTENER_OUTPUT_FILE = new Feature<string>(81, "http://saxon.sf.net/feature/traceListenerOutputFile");
        public static readonly Feature<bool> TRACE_OPTIMIZER_DECISIONS = new Feature<bool>(82, "http://saxon.sf.net/feature/trace-optimizer-decisions");
        public static readonly Feature<int> TREE_MODEL = new Feature<int>(83, "http://saxon.sf.net/feature/treeModel");
        public static readonly Feature<string> TREE_MODEL_NAME = new Feature<string>(84, "http://saxon.sf.net/feature/treeModelName");
        public static readonly Feature<IUnparsedTextURIResolver> UNPARSED_TEXT_URI_RESOLVER = new Feature<IUnparsedTextURIResolver>(85, "http://saxon.sf.net/feature/unparsedTextURIResolver");
        public static readonly Feature<string> UNPARSED_TEXT_URI_RESOLVER_CLASS = new Feature<string>(86, "http://saxon.sf.net/feature/unparsedTextURIResolverClass");
        public static readonly Feature<string> URI_RESOLVER_CLASS = new Feature<string>(87, "http://saxon.sf.net/feature/uriResolverClass");
        public static readonly Feature<bool> USE_PI_DISABLE_OUTPUT_ESCAPING = new Feature<bool>(88, "http://saxon.sf.net/feature/use-pi-disable-output-escaping");
        public static readonly Feature<bool> USE_TYPED_VALUE_CACHE = new Feature<bool>(89, "http://saxon.sf.net/feature/use-typed-value-cache");
        public static readonly Feature<bool> USE_XSI_SCHEMA_LOCATION = new Feature<bool>(90, "http://saxon.sf.net/feature/useXsiSchemaLocation");
        public static readonly Feature<bool> VALIDATION_COMMENTS = new Feature<bool>(91, "http://saxon.sf.net/feature/validation-comments");
        public static readonly Feature<bool> VALIDATION_WARNINGS = new Feature<bool>(92, "http://saxon.sf.net/feature/validation-warnings");
        public static readonly Feature<bool> VERSION_WARNING = new Feature<bool>(93, "http://saxon.sf.net/feature/version-warning");
        public static readonly Feature<bool> XINCLUDE = new Feature<bool>(94, "http://saxon.sf.net/feature/xinclude-aware");
        public static readonly Feature<string> XML_VERSION = new Feature<string>(95, "http://saxon.sf.net/feature/xml-version");
        public static readonly Feature<bool> XML_PARSER_FEATURE = new Feature<bool>(96, "http://saxon.sf.net/feature/parserFeature?uri=");
        public static readonly Feature<bool> XML_PARSER_PROPERTY = new Feature<bool>(97, "http://saxon.sf.net/feature/parserProperty?uri=");
        public static readonly Feature<bool> XQUERY_ALLOW_UPDATE = new Feature<bool>(98, "http://saxon.sf.net/feature/xqueryAllowUpdate");
        public static readonly Feature<string> XQUERY_CONSTRUCTION_MODE = new Feature<string>(99, "http://saxon.sf.net/feature/xqueryConstructionMode");
        public static readonly Feature<object> XQUERY_DEFAULT_ELEMENT_NAMESPACE = new Feature<object>(100, "http://saxon.sf.net/feature/xqueryDefaultElementNamespace");
        public static readonly Feature<object> XQUERY_DEFAULT_FUNCTION_NAMESPACE = new Feature<object>(101, "http://saxon.sf.net/feature/xqueryDefaultFunctionNamespace");
        public static readonly Feature<bool> XQUERY_EMPTY_LEAST = new Feature<bool>(102, "http://saxon.sf.net/feature/xqueryEmptyLeast");
        public static readonly Feature<bool> XQUERY_INHERIT_NAMESPACES = new Feature<bool>(103, "http://saxon.sf.net/feature/xqueryInheritNamespaces");
        public static readonly Feature<bool> XQUERY_MULTIPLE_MODULE_IMPORTS = new Feature<bool>(104, "http://saxon.sf.net/feature/xqueryMultipleModuleImports");
        public static readonly Feature<bool> XQUERY_PRESERVE_BOUNDARY_SPACE = new Feature<bool>(105, "http://saxon.sf.net/feature/xqueryPreserveBoundarySpace");
        public static readonly Feature<bool> XQUERY_PRESERVE_NAMESPACES = new Feature<bool>(106, "http://saxon.sf.net/feature/xqueryPreserveNamespaces");
        public static readonly Feature<string> XQUERY_REQUIRED_CONTEXT_ITEM_TYPE = new Feature<string>(107, "http://saxon.sf.net/feature/xqueryRequiredContextItemType");
        public static readonly Feature<bool> XQUERY_SCHEMA_AWARE = new Feature<bool>(108, "http://saxon.sf.net/feature/xquerySchemaAware");
        public static readonly Feature<string> XQUERY_STATIC_ERROR_LISTENER_CLASS = new Feature<string>(109, "http://saxon.sf.net/feature/xqueryStaticErrorListenerClass");
        public static readonly Feature<string> XQUERY_VERSION = new Feature<string>(110, "http://saxon.sf.net/feature/xqueryVersion");
        public static readonly Feature<string> XSD_VERSION = new Feature<string>(111, "http://saxon.sf.net/feature/xsd-version");
        public static readonly Feature<bool> XSLT_ENABLE_ASSERTIONS = new Feature<bool>(112, "http://saxon.sf.net/feature/enableAssertions");
        public static readonly Feature<string> XSLT_INITIAL_MODE = new Feature<string>(113, "http://saxon.sf.net/feature/initialMode");
        public static readonly Feature<string> XSLT_INITIAL_TEMPLATE = new Feature<string>(114, "http://saxon.sf.net/feature/initialTemplate");
        public static readonly Feature<bool> XSLT_SCHEMA_AWARE = new Feature<bool>(115, "http://saxon.sf.net/feature/xsltSchemaAware");
        public static readonly Feature<string> XSLT_STATIC_ERROR_LISTENER_CLASS = new Feature<string>(116, "http://saxon.sf.net/feature/stylesheetErrorListener");
        public static readonly Feature<string> XSLT_STATIC_URI_RESOLVER_CLASS = new Feature<string>(117, "http://saxon.sf.net/feature/stylesheetURIResolver");
        public static readonly Feature<string> XSLT_VERSION = new Feature<string>(118, "http://saxon.sf.net/feature/xsltVersion");
        public static readonly Feature<int> REGEX_BACKTRACKING_LIMIT = new Feature<int>(119, "http://saxon.sf.net/feature/regexBacktrackingLimit");
        public static readonly Feature<int> XPATH_VERSION_FOR_XSD = new Feature<int>(120, "http://saxon.sf.net/feature/xpathVersionForXsd");
        public static readonly Feature<int> XPATH_VERSION_FOR_XSLT = new Feature<int>(121, "http://saxon.sf.net/feature/xpathVersionForXslt");
        public static readonly Feature<int> THRESHOLD_FOR_FUNCTION_INLINING = new Feature<int>(122, "http://saxon.sf.net/feature/thresholdForFunctionInlining");
        public static readonly Feature<int> THRESHOLD_FOR_HOTSPOT_BYTE_CODE = new Feature<int>(123, "http://saxon.sf.net/feature/thresholdForHotspotByteCode");
        public static readonly Feature<object> ALLOWED_PROTOCOLS = new Feature<object>(124, "http://saxon.sf.net/feature/allowedProtocols");
        public static readonly Feature<bool> RETAIN_NODE_FOR_DIAGNOSTICS = new Feature<bool>(125, "http://saxon.sf.net/feature/retainNodeForDiagnostics");
        public static readonly Feature<bool> ALLOW_UNRESOLVED_SCHEMA_COMPONENTS = new Feature<bool>(126, "http://saxon.sf.net/feature/allowUnresolvedSchemaComponents");
        public static readonly Feature<string> ZIP_URI_PATTERN = new Feature<string>(127, "http://saxon.sf.net/feature/zipUriPattern");
        public static readonly Feature<object> RESOURCE_RESOLVER = new Feature<object>(128, "http://saxon.sf.net/feature/saxon-resource-resolver");
        public static readonly Feature<string> RESOURCE_RESOLVER_CLASS = new Feature<string>(129, "http://saxon.sf.net/feature/saxon-resource-resolver-class"); // AUTO-GENERATED FROM FeatureKeys.xml - DO NOT EDIT THIS FILE
        public readonly int code;
        public readonly string name;
        private Feature(int code, string name)
        {
            this.code = code;
            this.name = name;
        }
    }
}