////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using OutSmart.DAXon.Events;
using OutSmart.DAXon.Core;
using OutSmart.DAXon.Expressions;
using OutSmart.DAXon.Expressions.Parsing;
using OutSmart.DAXon.Functions;
using OutSmart.DAXon.Model;
using OutSmart.DAXon.Patterns;
using OutSmart.DAXon.Api;
using OutSmart.DAXon.Text;
using OutSmart.DAXon.Tracing;
using OutSmart.DAXon.Transformation;
using OutSmart.DAXon.Trees.Utilities;
using OutSmart.DAXon.Values;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Expressions.Elaboration;
using OutSmart.DAXon.Types;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Expressions.Instructions
{
    internal sealed class ValueOf : SimpleNodeConstructor
    {
        private int options;
        private bool numberingInstruction = false; // set to true if generated by xsl:number
        private readonly bool noNodeIfEmpty;

        public override int InstructionNameCode
        {
            get
            {
                if (numberingInstruction)
                {
                    return StandardNames.XSL_NUMBER;
                }
                else if (Select is StringLiteral)
                {
                    return StandardNames.XSL_TEXT;
                }
                else
                {
                    return StandardNames.XSL_VALUE_OF;
                }
            }
        }

        //
        public override int IntrinsicDependencies
        {
            get
            {
                int d = base.IntrinsicDependencies;
                if (IsDisableOutputEscaping())
                {

                    // Bug 2312 : prevent extraction of global variables
                    d |= StaticProperty.DEPENDS_ON_ASSIGNABLE_GLOBALS;
                }

                return d;
            }
        }
        public ValueOf(Expression select, bool disable, bool noNodeIfEmpty)
        {
            Select = select;
            options = disable ? ReceiverOption.DISABLE_ESCAPING : ReceiverOption.NONE;
            this.noNodeIfEmpty = noNodeIfEmpty;
            AdoptChildExpression(select);

            // If value is @fixed, test whether there are any special characters that might need to be
            // escaped when the time comes for serialization
            if (select is StringLiteral)
            {
                UnicodeString val = ((StringLiteral)select).GetString();
                bool special = val.IndexWhere((c) => c < 33 || c > 126 || c == '<' || c == '>' || c == '&', 0) >= 0;
                if (!special)
                {
                    options |= ReceiverOption.NO_SPECIAL_CHARS;
                }
            }
        }

        public void SetIsNumberingInstruction()
        {
            numberingInstruction = true;
        }

        public bool IsNumberingInstruction()
        {
            return numberingInstruction;
        }

        public bool IsNoNodeIfEmpty()
        {
            return noNodeIfEmpty;
        }

        public override string ToShortString()
        {
            if (Select is StringLiteral)
            {
                return "text{" + Err.Depict(((StringLiteral)Select).GroundedValue) + "}";
            }
            else
            {
                return base.ToShortString();
            }
        }

        public override void GatherProperties(Action<string, object> consumer)
        {
            if (Select is StringLiteral)
            {
                consumer("text",(((StringLiteral)Select).GroundedValue.UnicodeStringValue));
            }
        }

        public int GetOptions()
        {
            return options;
        }

        public bool IsDisableOutputEscaping()
        {
            return ReceiverOption.Contains(options, ReceiverOption.DISABLE_ESCAPING);
        }

        public override Types.ItemType GetItemType()
        {
            return NodeKindTest.TEXT;
        }

        protected override int ComputeCardinality()
        {
            if (noNodeIfEmpty)
            {
                return StaticProperty.ALLOWS_ZERO_OR_ONE;
            }
            else
            {
                return StaticProperty.EXACTLY_ONE;
            }
        }

        public override void LocalTypeCheck(ExpressionVisitor visitor, ContextItemStaticInfo contextItemType)
        {
        }

        //
        public override Expression Copy(RebindingMap rebindings)
        {
            ValueOf exp = new ValueOf(Select.Copy(rebindings), ReceiverOption.Contains(options, ReceiverOption.DISABLE_ESCAPING), noNodeIfEmpty);
            ExpressionTool.CopyLocationInfo(this, exp);
            if (numberingInstruction)
            {
                exp.SetIsNumberingInstruction();
            }

            return exp;
        }

        //
        public override void CheckPermittedContents(ISchemaType parentType, bool whole)
        {

            // if the expression is a constant value, check that it is valid for the type
            if (Select is Literal)
            {
                IGroundedValue selectValue = ((Literal)Select).GroundedValue;
                ISimpleType stype = null;
                if (parentType is ISimpleType && whole)
                {
                    stype = (ISimpleType)parentType;
                }
                else if (parentType is IComplexType && ((IComplexType)parentType).IsSimpleContent())
                {
                    stype = ((IComplexType)parentType).SimpleContentType;
                }

                if (whole && stype != null && !stype.IsNamespaceSensitive())
                {

                    // Can't validate namespace-sensitive content statically
                    ValidationFailure err = stype.ValidateContent(selectValue.UnicodeStringValue, null, GetConfiguration().GetConversionRules());
                    if (err != null)
                    {
                        err.Locator = GetLocation();
                        err.SetErrorCode(IsXSLT() ? "XTTE1540" : "XQDY0027");
                        throw err.MakeException();
                    }

                    return;
                }

                if (parentType is IComplexType && !((IComplexType)parentType).IsSimpleContent() && !((IComplexType)parentType).IsMixedContent() && !Whitespace.IsAllWhite(selectValue.UnicodeStringValue))
                {
                    throw new XPathException("The containing element must be of type " + parentType.Description + ", which does not allow text content " + Err.Wrap(selectValue.UnicodeStringValue)).WithLocation(GetLocation()).AsTypeError();
                }
            }
            else
            {
            }
        }

        //
        public Expression ConvertToCastAsString()
        {
            if (noNodeIfEmpty || !Cardinality.AllowsZero(Select.GetCardinality()))
            {
                return new CastExpression(Select, BuiltInAtomicType.UNTYPED_ATOMIC, true);
            }
            else
            {

                // must return zero-length string rather than () if empty
                Expression sf = SystemFunction.MakeCall("string", GetRetainedStaticContext(), Select);
                return new CastExpression(sf, BuiltInAtomicType.UNTYPED_ATOMIC, false);
            }
        }

        //
        public override void ProcessValue(UnicodeString value, Outputter output, IXPathContext context)
        {
            output.Characters(value, GetLocation(), options);
        }

        //
        public override IItem EvaluateItem(IXPathContext context)
        {
            try
            {
                IItem content = Select.MakeElaborator().ElaborateForItem().Eval(context);
                return MakeTextNode(content, noNodeIfEmpty, IsDisableOutputEscaping(), context);
            }
            catch (XPathException err)
            {
                throw err.MaybeWithLocation(GetLocation()).MaybeWithContext(context);
            }
        }

        //
        private static NodeInfo MakeTextNode(IItem content, bool noNodeIfEmpty, bool doe, IXPathContext context)
        {
            UnicodeString val;
            if (content == null)
            {
                if (noNodeIfEmpty)
                {
                    return null;
                }
                else
                {
                    val = EmptyUnicodeString.GetInstance();
                }
            }
            else
            {
                val = content.UnicodeStringValue;
            }

            Orphan o = new Orphan(context.GetConfiguration());
            o.SetNodeKind(Types.Type.TEXT);
            o.SetStringValue(val);
            if (doe)
            {
                o.SetDisableOutputEscaping(true);
            }

            return o;
        }

        //
        public override void Export(ExpressionPresenter @out)
        {
            @out.StartElement("valueOf", this);
            string flags = "";
            if (IsDisableOutputEscaping())
            {
                flags += "d";
            }

            if (ReceiverOption.Contains(options, ReceiverOption.NO_SPECIAL_CHARS))
            {
                flags += "S";
            }

            if (noNodeIfEmpty)
            {
                flags += "e";
            }

            if (IsLocal())
            {
                flags += "l";
            }

            if (!(flags.Length == 0))
            {
                @out.EmitAttribute("flags", flags);
            }

            Select.Export(@out);
            @out.EndElement();
        }

        //
        public override Elaborator GetElaborator()
        {
            return new ValueOfElaborator();
        }

        //
        private class ValueOfElaborator : SimpleNodePushElaborator
        {
            public override IPushEvaluator ElaborateForPush()
            {
                ValueOf expr = (ValueOf)GetExpression();
                ILocation loc = expr.GetLocation();
                bool noNodeIfEmpty = expr.noNodeIfEmpty;
                int options = expr.GetOptions();
                if (noNodeIfEmpty)
                {
                    IItemEvaluator contentEval = expr.Select.MakeElaborator().ElaborateForItem();
                    return (output, context) =>
                    {
                        try
                        {
                            IItem value = contentEval.Eval(context);
                            if (value != null)
                            {
                                output.Characters(value.UnicodeStringValue, loc, options);
                            }

                            return null;
                        }
                        catch (XPathException e)
                        {
                            throw e.MaybeWithLocation(expr.Select.GetLocation());
                        }
                    };
                }
                else if (expr.Select.GetItemType() == BuiltInAtomicType.STRING && !expr.IsDisableOutputEscaping() && !Cardinality.AllowsZero(expr.GetCardinality()) && Cardinality.AllowsMany(expr.GetCardinality()))
                {

                    // Try to stream the value direct to the serializer where possible
                    // Note: see bug 4944, which is why we don't use this path if the select
                    //       expression might return an empty sequence.
                    // A single string (the dominant case: value-of over a scalar function like
                    // normalize-space) skips this and takes the else branch, which evaluates the
                    // string and calls output.Characters directly - the streaming Outputter this
                    // path allocates PER CALL only earns its keep for a genuine multi-item sequence.
                    IPushEvaluator contentEval = expr.Select.MakeElaborator().ElaborateForPush();
                    return (output, context) =>
                    {
                        try
                        {
                            Outputter streamer = new TextNodeOutputStreamer(output, loc, options);
                            return contentEval.ProcessLeavingTail(streamer, context);
                        }
                        catch (XPathException e)
                        {
                            throw e.MaybeWithLocation(expr.Select.GetLocation());
                        }
                    };
                }
                else
                {
                    // value-template shapes over a child element take the fused TinyTree read
                    // (no axis/atomizer/converter iterators per call); null = no match
                    IUnicodeStringEvaluator contentEval = Elaboration.FusedChildValue.TryFuse(expr.Select)
                        ?? expr.Select.MakeElaborator().ElaborateForUnicodeString(true);
                    return (output, context) =>
                    {
                        try
                        {
                            UnicodeString value = contentEval.Eval(context);
                            output.Characters(value, loc, options);
                            return null;
                        }
                        catch (XPathException e)
                        {
                            throw e.MaybeWithLocation(expr.Select.GetLocation());
                        }
                    };
                }
            }

            public override IItemEvaluator ElaborateForItem()
            {
                ValueOf expr = (ValueOf)GetExpression();
                IItemEvaluator contentEval = expr.Select.MakeElaborator().ElaborateForItem();
                bool noNodeIfEmpty = expr.noNodeIfEmpty;
                bool doe = expr.IsDisableOutputEscaping();
                return (context) =>
                {
                    try
                    {
                        return ValueOf.MakeTextNode(contentEval.Eval(context), noNodeIfEmpty, doe, context);
                    }
                    catch (XPathException e)
                    {
                        throw e.MaybeWithLocation(expr.Select.GetLocation());
                    }
                };
            }
        }

        //
        private class TextNodeOutputStreamer : ProxyOutputter
        {
            private readonly ILocation instructionLoc;
            private readonly int options;
            public TextNodeOutputStreamer(Outputter output, ILocation instructionLoc, int options) : base(output)
            {
                this.instructionLoc = instructionLoc;
                this.options = options;
            }

            public override void Append(IItem item)
            {
                NextOutputter.Characters(item.UnicodeStringValue, instructionLoc, options);
            }

            public override void Append(IItem item, ILocation loc, int properties)
            {
                ILocation location = loc.GetLineNumber() == -1 ? instructionLoc : loc;
                NextOutputter.Characters(item.UnicodeStringValue, location, properties | options);
            }

            public override IUniStringConsumer GetStringReceiver(bool asTextNode, ILocation loc)
            {
                ILocation location = loc.GetLineNumber() == -1 ? instructionLoc : loc;
                return NextOutputter.GetStringReceiver(true, location);
            }
        }
    }
}
