////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using OutSmart.DAXon.Expressions.Parsing;
using OutSmart.DAXon.Model;
using OutSmart.DAXon.Transformation;
using OutSmart.DAXon.Types;
using OutSmart.DAXon.Core;
using OutSmart.DAXon.Collections;
using OutSmart.DAXon.Internal.Numerics;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Functions;
using OutSmart.DAXon.Values;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
using System.Numerics;
namespace OutSmart.DAXon.Expressions
{
    internal abstract class Calculator
    {
        public const int PLUS = 0;
        public const int MINUS = 1;
        public const int TIMES = 2;
        public const int DIV = 3;
        public const int MOD = 4;
        public const int IDIV = 5;

        public static readonly Calculator[] ANY_ANY = new Calculator[]
        {
            new AnyPlusAny(),
            new AnyMinusAny(),
            new AnyTimesAny(),
            new AnyDivAny(),
            new AnyModAny(),
            new AnyIdivAny()
        };
        // NOTE: these fields are public because they are referenced from the Java code generated by the XQuery compiler
        /// <summary>
        /// Calculators used when the first operand is a double
        /// </summary>
        public static readonly Calculator[] DOUBLE_DOUBLE = new Calculator[]
        {
            new DoublePlusDouble(),
            new DoubleMinusDouble(),
            new DoubleTimesDouble(),
            new DoubleDivDouble(),
            new DoubleModDouble(),
            new DoubleIdivDouble()
        };

        public static readonly Calculator[] DOUBLE_FLOAT = DOUBLE_DOUBLE;
        public static readonly Calculator[] DOUBLE_DECIMAL = DOUBLE_DOUBLE;
        public static readonly Calculator[] DOUBLE_INTEGER = DOUBLE_DOUBLE;
        /// <summary>
        /// Calculators used when the first operand is a float
        /// </summary>
        public static readonly Calculator[] FLOAT_DOUBLE = DOUBLE_DOUBLE;
        public static readonly Calculator[] FLOAT_FLOAT = new Calculator[]
        {
            new FloatPlusFloat(),
            new FloatMinusFloat(),
            new FloatTimesFloat(),
            new FloatDivFloat(),
            new FloatModFloat(),
            new FloatIdivFloat()
        };
        public static readonly Calculator[] FLOAT_DECIMAL = FLOAT_FLOAT;
        //public final static Calculator[] FLOAT_PDECIMAL = FLOAT_FLOAT;
        public static readonly Calculator[] FLOAT_INTEGER = FLOAT_FLOAT;
        /// <summary>
        /// Calculators used when the first operand is a decimal
        /// </summary>
        public static readonly Calculator[] DECIMAL_DOUBLE = DOUBLE_DOUBLE;
        public static readonly Calculator[] DECIMAL_FLOAT = FLOAT_FLOAT;
        public static readonly Calculator[] DECIMAL_DECIMAL = new Calculator[]
        {
            new DecimalPlusDecimal(),
            new DecimalMinusDecimal(),
            new DecimalTimesDecimal(),
            new DecimalDivDecimal(),
            new DecimalModDecimal(),
            new DecimalIdivDecimal()
        };
        public static readonly Calculator[] DECIMAL_INTEGER = DECIMAL_DECIMAL;
        /// <summary>
        /// Calculators used when the first operand is an integer
        /// </summary>
        public static readonly Calculator[] INTEGER_DOUBLE = DOUBLE_DOUBLE;
        public static readonly Calculator[] INTEGER_FLOAT = FLOAT_FLOAT;
        public static readonly Calculator[] INTEGER_DECIMAL = DECIMAL_DECIMAL;
        public static readonly Calculator[] INTEGER_INTEGER = new Calculator[]
        {
            new IntegerPlusInteger(),
            new IntegerMinusInteger(),
            new IntegerTimesInteger(),
            new IntegerDivInteger(),
            new IntegerModInteger(),
            new IntegerIdivInteger()
        };
        /// <summary>
        /// Calculators used when both operands are xs:dateTime, xs:date, or xs:time
        /// </summary>
        public static readonly Calculator[] DATETIME_DATETIME = new Calculator[]
        {
            null,
            new DateTimeMinusDateTime(),
            null,
            null,
            null,
            null
        };
        public static readonly Calculator[] DATETIME_DURATION = new Calculator[]
        {
            new DateTimePlusDuration(),
            new DateTimeMinusDuration(),
            null,
            null,
            null,
            null
        };
        public static readonly Calculator[] DURATION_DATETIME = new Calculator[]
        {
            new DurationPlusDateTime(),
            null,
            null,
            null,
            null,
            null
        };
        /// <summary>
        /// Calculators used when the both operands are durations
        /// </summary>
        public static readonly Calculator[] DURATION_DURATION = new Calculator[]
        {
            new DurationPlusDuration(),
            new DurationMinusDuration(),
            null,
            new DurationDivDuration(),
            null,
            null
        };
        /// <summary>
        /// Calculators used when the first operand is a duration and the second is numeric
        /// </summary>
        public static readonly Calculator[] DURATION_NUMERIC = new Calculator[]
        {
            null,
            null,
            new DurationTimesNumeric(),
            new DurationDivNumeric(),
            null,
            null
        };
        /// <summary>
        /// Calculators used when the second operand is a duration and the first is numeric
        /// </summary>
        public static readonly Calculator[] NUMERIC_DURATION = new Calculator[]
        {
            null,
            null,
            new NumericTimesDuration(),
            null,
            null,
            null
        };
        /// <summary>
        /// Table mapping argument types to the Calculator class used to implement them
        /// </summary>
        private static readonly IntHashMap<Calculator[]> table = new IntHashMap<Calculator[]>(100);

        static Calculator()
        {
            Def(StandardNames.XS_DOUBLE, StandardNames.XS_DOUBLE, DOUBLE_DOUBLE);
            Def(StandardNames.XS_DOUBLE, StandardNames.XS_FLOAT, DOUBLE_FLOAT);
            Def(StandardNames.XS_DOUBLE, StandardNames.XS_DECIMAL, DOUBLE_DECIMAL);
            Def(StandardNames.XS_DOUBLE, StandardNames.XS_INTEGER, DOUBLE_INTEGER);
            Def(StandardNames.XS_FLOAT, StandardNames.XS_DOUBLE, FLOAT_DOUBLE);
            Def(StandardNames.XS_FLOAT, StandardNames.XS_FLOAT, FLOAT_FLOAT);
            Def(StandardNames.XS_FLOAT, StandardNames.XS_DECIMAL, FLOAT_DECIMAL);
            Def(StandardNames.XS_FLOAT, StandardNames.XS_INTEGER, FLOAT_INTEGER);
            Def(StandardNames.XS_DECIMAL, StandardNames.XS_DOUBLE, DECIMAL_DOUBLE);
            Def(StandardNames.XS_DECIMAL, StandardNames.XS_FLOAT, DECIMAL_FLOAT);
            Def(StandardNames.XS_DECIMAL, StandardNames.XS_DECIMAL, DECIMAL_DECIMAL);
            Def(StandardNames.XS_DECIMAL, StandardNames.XS_INTEGER, DECIMAL_INTEGER);
            Def(StandardNames.XS_INTEGER, StandardNames.XS_DOUBLE, INTEGER_DOUBLE);
            Def(StandardNames.XS_INTEGER, StandardNames.XS_FLOAT, INTEGER_FLOAT);
            Def(StandardNames.XS_INTEGER, StandardNames.XS_DECIMAL, INTEGER_DECIMAL);
            Def(StandardNames.XS_INTEGER, StandardNames.XS_INTEGER, INTEGER_INTEGER);
            Def(StandardNames.XS_DATE_TIME, StandardNames.XS_DATE_TIME, DATETIME_DATETIME);
            Def(StandardNames.XS_DATE_TIME, StandardNames.XS_DURATION, DATETIME_DURATION);
            Def(StandardNames.XS_DURATION, StandardNames.XS_DATE_TIME, DURATION_DATETIME);
            Def(StandardNames.XS_DURATION, StandardNames.XS_DURATION, DURATION_DURATION);
            Def(StandardNames.XS_DURATION, StandardNames.XS_DOUBLE, DURATION_NUMERIC);
            Def(StandardNames.XS_DURATION, StandardNames.XS_FLOAT, DURATION_NUMERIC);
            Def(StandardNames.XS_DURATION, StandardNames.XS_DECIMAL, DURATION_NUMERIC);
            Def(StandardNames.XS_DURATION, StandardNames.XS_INTEGER, DURATION_NUMERIC);
            Def(StandardNames.XS_DOUBLE, StandardNames.XS_DURATION, NUMERIC_DURATION);
            Def(StandardNames.XS_FLOAT, StandardNames.XS_DURATION, NUMERIC_DURATION);
            Def(StandardNames.XS_DECIMAL, StandardNames.XS_DURATION, NUMERIC_DURATION);
            Def(StandardNames.XS_INTEGER, StandardNames.XS_DURATION, NUMERIC_DURATION);
        }
        public virtual string Code()
        {
            string name = GetType().Name;
            return name.Replace("Any", "a").Replace("Double", "d").Replace("Float", "f").Replace("Decimal", "c").Replace("Integer", "i").Replace("Numeric", "n").Replace("DateTime", "t").Replace("Duration", "u").Replace("Plus", "+").Replace("Minus", "-").Replace("Times", "*").Replace("Div", "/").Replace("Idiv", "~").Replace("Mod", "%");
        }
        private static void Def(int typeA, int typeB, Calculator[] calculatorSet)
        {
            int key = (typeA & 0xffff) << 16 | (typeB & 0xffff);
            table.Put(key, calculatorSet);

            // As well as the entries added directly, we also add derived entries for other types
            // considered primitive
            if (typeA == StandardNames.XS_DURATION)
            {
                Def(StandardNames.XS_DAY_TIME_DURATION, typeB, calculatorSet);
                Def(StandardNames.XS_YEAR_MONTH_DURATION, typeB, calculatorSet);
            }

            if (typeB == StandardNames.XS_DURATION)
            {
                Def(typeA, StandardNames.XS_DAY_TIME_DURATION, calculatorSet);
                Def(typeA, StandardNames.XS_YEAR_MONTH_DURATION, calculatorSet);
            }

            if (typeA == StandardNames.XS_DATE_TIME)
            {
                Def(StandardNames.XS_DATE, typeB, calculatorSet);
                Def(StandardNames.XS_TIME, typeB, calculatorSet);
            }

            if (typeB == StandardNames.XS_DATE_TIME)
            {
                Def(typeA, StandardNames.XS_DATE, calculatorSet);
                Def(typeA, StandardNames.XS_TIME, calculatorSet);
            }

            if (typeA == StandardNames.XS_DOUBLE)
            {
                Def(StandardNames.XS_UNTYPED_ATOMIC, typeB, calculatorSet);
            }

            if (typeB == StandardNames.XS_DOUBLE)
            {
                Def(typeA, StandardNames.XS_UNTYPED_ATOMIC, calculatorSet);
            }
        }

        public static Calculator GetCalculator(int typeA, int typeB, int @operator, bool mustResolve)
        {
            int key = (typeA & 0xffff) << 16 | (typeB & 0xffff);
            Calculator[] set = table[key];
            if (set == null)
            {
                if (mustResolve)
                {
                    return null;
                }
                else
                {
                    return ANY_ANY[@operator];
                }
            }
            else
            {
                return set[@operator];
            }
        }

        public abstract AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c);
        public abstract IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB);

        public static BigDecimalValue DecimalDivide(NumericValue a, NumericValue b)
        {
            if (b.Signum() == 0)
            {
                throw new XPathException("Decimal divide by zero", "FOAR0001");
            }

            BigDecimal A = a.GetDecimalValue();
            BigDecimal B = b.GetDecimalValue();
            BigDecimal result = InternalDecimalDivide(A, B);
            return new BigDecimalValue(result);
        }

        private static BigDecimal InternalDecimalDivide(BigDecimal A, BigDecimal B)
        {
            int scale = Math.Max(BigDecimalValue.DIVIDE_PRECISION, A.Scale() - B.Scale() + BigDecimalValue.DIVIDE_PRECISION);
            return A.Divide(B, scale, RoundingMode.HALF_DOWN);
        }
        /// <summary>
        /// Marker interface for operations on doubles
        /// </summary>
        internal interface IDoubleOpDouble
        {
        }
        /// <summary>
        /// Arithmetic: anyAtomicType + AnyAtomicType
        /// </summary>
        internal class AnyPlusAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, PLUS, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for + operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: anyAtomicType - AnyAtomicType
        /// </summary>
        internal class AnyMinusAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, MINUS, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for - operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: anyAtomicType * AnyAtomicType
        /// </summary>
        internal class AnyTimesAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, TIMES, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for * operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: anyAtomicType div AnyAtomicType
        /// </summary>
        internal class AnyDivAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, DIV, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for div operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: anyAtomicType mod AnyAtomicType
        /// </summary>
        internal class AnyModAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, MOD, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for mod operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: anyAtomicType idiv AnyAtomicType
        /// </summary>
        internal class AnyIdivAny : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                Calculator calc = GetCalculator(a.GetItemType().PrimitiveType, b.GetItemType().PrimitiveType, IDIV, true);
                if (calc == null)
                {
                    throw new XPathException("Unsuitable types for idiv operation (" + Types.Type.DisplayTypeName(a) + ", " + Types.Type.DisplayTypeName(b) + ")", "XPTY0004", c);
                }
                else
                {
                    return calc.Compute(a, b, c);
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.ANY_ATOMIC;
            }
        }

        /// <summary>
        /// Arithmetic: double + double (including types that promote to double)
        /// </summary>
        internal class DoublePlusDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new DoubleValue(((NumericValue)a).GetDoubleValue() + ((NumericValue)b).GetDoubleValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DOUBLE;
            }
        }

        /// <summary>
        /// Arithmetic: double - double (including types that promote to double)
        /// </summary>
        internal class DoubleMinusDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new DoubleValue(((NumericValue)a).GetDoubleValue() - ((NumericValue)b).GetDoubleValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DOUBLE;
            }
        }

        /// <summary>
        /// Arithmetic: double * double (including types that promote to double)
        /// </summary>
        internal class DoubleTimesDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new DoubleValue(((NumericValue)a).GetDoubleValue() * ((NumericValue)b).GetDoubleValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DOUBLE;
            }
        }

        /// <summary>
        /// Arithmetic: double div double (including types that promote to double)
        /// </summary>
        internal class DoubleDivDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new DoubleValue(((NumericValue)a).GetDoubleValue() / ((NumericValue)b).GetDoubleValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DOUBLE;
            }
        }

        /// <summary>
        /// Arithmetic: double mod double (including types that promote to double)
        /// </summary>
        internal class DoubleModDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new DoubleValue(((NumericValue)a).GetDoubleValue() % ((NumericValue)b).GetDoubleValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DOUBLE;
            }
        }

        /// <summary>
        /// Arithmetic: double idiv double (including types that promote to double)
        /// </summary>
        private class DoubleIdivDouble : Calculator, IDoubleOpDouble
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                double A = ((NumericValue)a).GetDoubleValue();
                double B = ((NumericValue)b).GetDoubleValue();
                if (B == 0)
                {
                    throw new XPathException("Integer division by zero", "FOAR0001", c);
                }

                if (double.IsNaN(A) || double.IsInfinity(A))
                {
                    throw new XPathException("First operand of idiv is NaN or infinity", "FOAR0002", c);
                }

                if (double.IsNaN(B))
                {
                    throw new XPathException("Second operand of idiv is NaN", "FOAR0002", c);
                }

                return IntegerValue.FromDouble(A / B).AsAtomic();
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: float + float (including types that promote to float)
        /// </summary>
        internal class FloatPlusFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new FloatValue(((NumericValue)a).GetFloatValue() + ((NumericValue)b).GetFloatValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.FLOAT;
            }
        }

        /// <summary>
        /// Arithmetic: float - float (including types that promote to float)
        /// </summary>
        internal class FloatMinusFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new FloatValue(((NumericValue)a).GetFloatValue() - ((NumericValue)b).GetFloatValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.FLOAT;
            }
        }

        /// <summary>
        /// Arithmetic: float * float (including types that promote to float)
        /// </summary>
        internal class FloatTimesFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new FloatValue(((NumericValue)a).GetFloatValue() * ((NumericValue)b).GetFloatValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.FLOAT;
            }
        }

        /// <summary>
        /// Arithmetic: float div float (including types that promote to float)
        /// </summary>
        internal class FloatDivFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new FloatValue(((NumericValue)a).GetFloatValue() / ((NumericValue)b).GetFloatValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.FLOAT;
            }
        }

        /// <summary>
        /// Arithmetic: float mod float (including types that promote to float)
        /// </summary>
        internal class FloatModFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return new FloatValue(((NumericValue)a).GetFloatValue() % ((NumericValue)b).GetFloatValue());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.FLOAT;
            }
        }

        /// <summary>
        /// Arithmetic: float idiv float (including types that promote to float)
        /// </summary>
        internal class FloatIdivFloat : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                float A = ((NumericValue)a).GetFloatValue();
                float B = ((NumericValue)b).GetFloatValue();
                if (B == 0)
                {
                    throw new XPathException("Integer division by zero", "FOAR0001", c);
                }

                if (float.IsNaN(A) || float.IsInfinity(A))
                {
                    throw new XPathException("First operand of idiv is NaN or infinity", "FOAR0002", c);
                }

                if (float.IsNaN(B))
                {
                    throw new XPathException("Second operand of idiv is NaN", "FOAR0002", c);
                }

                float quotient = A / B;
                if (float.IsInfinity(quotient))
                {

                    // bug 29171, test cbcl-numeric-idivide-008
                    return new DecimalIdivDecimal().Compute(new BigDecimalValue(((NumericValue)a).GetDecimalValue()), new BigDecimalValue(((NumericValue)b).GetDecimalValue()), c);
                }
                else
                {
                    return (IntegerValue)Converter.FloatToInteger.INSTANCE.Convert(new FloatValue(quotient)).AsAtomic();
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: decimal + decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalPlusDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is IntegerValue && b is IntegerValue)
                {
                    return ((IntegerValue)a).Plus((IntegerValue)b);
                }
                else
                {
                    return new BigDecimalValue(((NumericValue)a).GetDecimalValue() + ((NumericValue)b).GetDecimalValue());
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: decimal - decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalMinusDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is IntegerValue && b is IntegerValue)
                {
                    return ((IntegerValue)a).Minus((IntegerValue)b);
                }
                else
                {
                    return new BigDecimalValue(((NumericValue)a).GetDecimalValue() - ((NumericValue)b).GetDecimalValue());
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: decimal * decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalTimesDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is IntegerValue && b is IntegerValue)
                {
                    return ((IntegerValue)a).Times((IntegerValue)b);
                }
                else
                {
                    return new BigDecimalValue(((NumericValue)a).GetDecimalValue() * ((NumericValue)b).GetDecimalValue());
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: decimal div decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalDivDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return DecimalDivide((NumericValue)a, (NumericValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: decimal mod decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalModDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is IntegerValue && b is IntegerValue)
                {
                    return ((IntegerValue)a).Mod((IntegerValue)b);
                }

                if (((NumericValue)b).Signum() == 0)
                {
                    throw new XPathException("Decimal modulo zero", "FOAR0001", c);
                }

                BigDecimal A = ((NumericValue)a).GetDecimalValue();
                BigDecimal B = ((NumericValue)b).GetDecimalValue();
                return new BigDecimalValue(A.Remainder(B));
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: decimal idiv decimal (including types that promote to decimal, that @is, integer)
        /// </summary>
        internal class DecimalIdivDecimal : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is IntegerValue && b is IntegerValue)
                {
                    return ((IntegerValue)a).Idiv((IntegerValue)b);
                }

                BigDecimal A = ((NumericValue)a).GetDecimalValue();
                BigDecimal B = ((NumericValue)b).GetDecimalValue();
                if (B.Sign == 0)
                {
                    throw new XPathException("Integer division by zero", "FOAR0001", c);
                }

                BigInteger quot = A.DivideToIntegralValue(B).ToBigInteger();
                return BigIntegerValue.MakeIntegerValue(quot);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: integer + integer
        /// </summary>
        internal class IntegerPlusInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Plus((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: integer - integer
        /// </summary>
        internal class IntegerMinusInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Minus((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: integer * integer
        /// </summary>
        internal class IntegerTimesInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Times((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: integer div integer
        /// </summary>
        internal class IntegerDivInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Div((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: integer mod integer
        /// </summary>
        internal class IntegerModInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Mod((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: integer idiv integer
        /// </summary>
        internal class IntegerIdivInteger : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((IntegerValue)a).Idiv((IntegerValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.INTEGER;
            }
        }

        /// <summary>
        /// Arithmetic: date/time/dateTime - date/time/dateTime
        /// </summary>
        private class DateTimeMinusDateTime : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((CalendarValue)a).Subtract((CalendarValue)b, c);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DAY_TIME_DURATION;
            }
        }

        /// <summary>
        /// Arithmetic: date/time/dateTime + duration
        /// </summary>
        private class DateTimePlusDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((CalendarValue)a).Add((DurationValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }

        /// <summary>
        /// Arithmetic: date/time/dateTime - duration
        /// </summary>
        private class DateTimeMinusDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((CalendarValue)a).Add(((DurationValue)b).Negate());
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }

        /// <summary>
        /// Arithmetic: duration + date/time/dateTime
        /// </summary>
        private class DurationPlusDateTime : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((CalendarValue)b).Add((DurationValue)a);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeB;
            }
        }

        /// <summary>
        /// Arithmetic: duration + duration
        /// </summary>
        private class DurationPlusDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((DurationValue)a).Add((DurationValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }

        /// <summary>
        /// Arithmetic: duration - duration
        /// </summary>
        private class DurationMinusDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((DurationValue)a).Subtract((DurationValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }

        /// <summary>
        /// Arithmetic: duration div duration
        /// </summary>
        private class DurationDivDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                return ((DurationValue)a).Divide((DurationValue)b);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return BuiltInAtomicType.DECIMAL;
            }
        }

        /// <summary>
        /// Arithmetic: duration * number
        /// </summary>
        private class DurationTimesNumeric : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (b is Int64Value)
                {
                    return ((DurationValue)a).Multiply(((Int64Value)b).LongValue());
                }
                else if (b is DecimalValue)
                {
                    return ((DurationValue)a).Multiply(((DecimalValue)b).GetDecimalValue());
                }
                else
                {
                    return ((DurationValue)a).Multiply(((NumericValue)b).GetDoubleValue());
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }

        /// <summary>
        /// Arithmetic: number * duration
        /// </summary>
        private class NumericTimesDuration : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                if (a is Int64Value)
                {
                    return ((DurationValue)b).Multiply(((Int64Value)a).LongValue());
                }
                else
                {
                    return ((DurationValue)b).Multiply(((NumericValue)a).GetDoubleValue());
                }
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeB;
            }
        }

        /// <summary>
        /// Arithmetic: duration div number
        /// </summary>
        private class DurationDivNumeric : Calculator
        {
            public override AtomicValue Compute(AtomicValue a, AtomicValue b, IXPathContext c)
            {
                double d = 1 / ((NumericValue)b).GetDoubleValue();
                return ((DurationValue)a).Multiply(d);
            }

            public override IAtomicType GetResultType(IAtomicType typeA, IAtomicType typeB)
            {
                return typeA;
            }
        }
    }
}