////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2018-2023 Saxonica Limited
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using OutSmart.DAXon.Expressions.Elaboration;
using OutSmart.DAXon.Expressions.Parsing;
using OutSmart.DAXon.Model;
using OutSmart.DAXon.Tracing;
using OutSmart.DAXon.Transformation;
using OutSmart.DAXon.Types;
using OutSmart.DAXon.Values;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using OutSmart.DAXon.Events;
using OutSmart.DAXon.Functions;
using OutSmart.DAXon.Internal;
using OutSmart.DAXon.Internal.Collections;
namespace OutSmart.DAXon.Expressions
{
    /// <summary>
    /// A position() eq last() expression, generated by the optimizer.
    /// </summary>
    public sealed class IsLastExpression : Expression
    {
        private readonly bool condition;

        public bool Condition => condition;

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        public override int IntrinsicDependencies => StaticProperty.DEPENDS_ON_POSITION | StaticProperty.DEPENDS_ON_LAST;

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        public override int ImplementationMethod => EVALUATE_METHOD;

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        public override string ExpressionName => "isLast";

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        public override string StreamerName => "IsLastExpr";
        public IsLastExpression(bool condition)
        {
            this.condition = condition;
        }

        public override Expression TypeCheck(ExpressionVisitor visitor, ContextItemStaticInfo contextInfo)
        {
            return this;
        }

        public override Expression Optimize(ExpressionVisitor visitor, ContextItemStaticInfo contextItemType)
        {
            return this;
        }

        protected override int ComputeSpecialProperties()
        {
            int p = base.ComputeSpecialProperties();
            return p | StaticProperty.NO_NODES_NEWLY_CREATED;
        }

        public override IItem EvaluateItem(IXPathContext c)
        {
            return BooleanValue.Get(condition == c.IsAtLast());
        }

        public override bool EffectiveBooleanValue(IXPathContext context)
        {
            return condition == context.IsAtLast();
        }

        public override ItemType GetItemType()
        {
            return BuiltInAtomicType.BOOLEAN;
        }

        /// <summary>
        /// Determine the static cardinality
        /// </summary>
        protected override int ComputeCardinality()
        {
            return StaticProperty.EXACTLY_ONE;
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        public override Expression Copy(RebindingMap rebindings)
        {
            IsLastExpression exp = new IsLastExpression(condition);
            ExpressionTool.CopyLocationInfo(this, exp);
            return exp;
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        public override bool Equals(object other)
        {
            return other is IsLastExpression && ((IsLastExpression)other).condition == condition;
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        protected override int ComputeHashCode()
        {
            return condition ? 0x236b91a0 : 0x396b92a0;
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        public override void Export(ExpressionPresenter destination)
        {
            destination.StartElement("isLast", this);
            destination.EmitAttribute("test", condition ? "1" : "0");
            destination.EndElement();
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        public override string ToString()
        {
            if (condition)
            {
                return "isLast()";
            }
            else
            {
                return "isNotLast()";
            }
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Hashcode supporting equals()
        /// </summary>
        public override Elaborator GetElaborator()
        {
            return new IsLastElaborator();
        }

        /// <summary>
        /// Get the dependencies of this expression on the context
        /// </summary>
        /// <summary>
        /// Elaborator for an "isLast" expression, equivalent to {@code position() = last()} or {@code position() != last()}
        /// </summary>
        public class IsLastElaborator : BooleanElaborator
        {
            public override IBooleanEvaluator ElaborateForBoolean()
            {
                IsLastExpression expr = (IsLastExpression)GetExpression();
                if (expr.Condition)
                {
                    return (context) => context.IsAtLast();
                }
                else
                {
                    return (context) => !context.IsAtLast();
                }
            }
        }
    }
}
